-- fix_record_payment.sql
-- Idempotent Supabase repair script for liability payment RPCs.
-- Safe to run in Supabase SQL Editor as-is.
-- No DROP TABLE / no DELETE data statements included.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Required dependency tables
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    creditor_name TEXT NOT NULL,
    liability_type TEXT NOT NULL DEFAULT 'Hawlad',
    total_amount NUMERIC NOT NULL CHECK (total_amount > 0),
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    remaining_amount NUMERIC NOT NULL DEFAULT 0,
    due_date DATE NULL,
    emi_amount NUMERIC DEFAULT 0,
    duration_months INT DEFAULT 0,
    start_date DATE NULL,
    due_day INT NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Paid Off')),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.emi_installments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    liability_id BIGINT NOT NULL REFERENCES public.liabilities(id) ON DELETE CASCADE,
    installment_number INT NOT NULL,
    due_date DATE NOT NULL,
    expected_amount NUMERIC NOT NULL,
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Upcoming' CHECK (status IN ('Upcoming', 'Due', 'Partial', 'Paid', 'Overdue')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (liability_id, installment_number)
);

CREATE TABLE IF NOT EXISTS public.liability_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    liability_id BIGINT NOT NULL REFERENCES public.liabilities(id) ON DELETE CASCADE,
    emi_installment_id UUID NULL REFERENCES public.emi_installments(id) ON DELETE SET NULL,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    expense_id BIGINT NULL REFERENCES public.expenses(id) ON DELETE SET NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure the referenced expenses table exists for FK checks and payment-expense linking.
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- Missing-column safety for older DBs
-- -----------------------------------------------------------------------------
ALTER TABLE public.liabilities
    ADD COLUMN IF NOT EXISTS creditor_name TEXT,
    ADD COLUMN IF NOT EXISTS liability_type TEXT,
    ADD COLUMN IF NOT EXISTS total_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS paid_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS remaining_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS due_date DATE,
    ADD COLUMN IF NOT EXISTS emi_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS duration_months INT,
    ADD COLUMN IF NOT EXISTS start_date DATE,
    ADD COLUMN IF NOT EXISTS due_day INT,
    ADD COLUMN IF NOT EXISTS status TEXT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE public.emi_installments
    ADD COLUMN IF NOT EXISTS user_id UUID,
    ADD COLUMN IF NOT EXISTS liability_id BIGINT,
    ADD COLUMN IF NOT EXISTS installment_number INT,
    ADD COLUMN IF NOT EXISTS due_date DATE,
    ADD COLUMN IF NOT EXISTS expected_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS paid_amount NUMERIC,
    ADD COLUMN IF NOT EXISTS status TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE public.liability_payments
    ADD COLUMN IF NOT EXISTS user_id UUID,
    ADD COLUMN IF NOT EXISTS liability_id BIGINT,
    ADD COLUMN IF NOT EXISTS emi_installment_id UUID,
    ADD COLUMN IF NOT EXISTS payment_date DATE,
    ADD COLUMN IF NOT EXISTS amount NUMERIC,
    ADD COLUMN IF NOT EXISTS payment_method TEXT,
    ADD COLUMN IF NOT EXISTS expense_id BIGINT,
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_liabilities_user_id ON public.liabilities(user_id);
CREATE INDEX IF NOT EXISTS idx_emi_installments_user_id ON public.emi_installments(user_id);
CREATE INDEX IF NOT EXISTS idx_emi_installments_liability_id ON public.emi_installments(liability_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_user_id ON public.liability_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_liability_id ON public.liability_payments(liability_id);

-- -----------------------------------------------------------------------------
-- RLS and permissions
-- -----------------------------------------------------------------------------
ALTER TABLE public.liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emi_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liability_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can insert own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can update own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can delete own liabilities" ON public.liabilities;

CREATE POLICY "Users can select own liabilities" ON public.liabilities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liabilities" ON public.liabilities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liabilities" ON public.liabilities FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liabilities" ON public.liabilities FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can insert own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can update own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can delete own emi_installments" ON public.emi_installments;

CREATE POLICY "Users can select own emi_installments" ON public.emi_installments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own emi_installments" ON public.emi_installments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own emi_installments" ON public.emi_installments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own emi_installments" ON public.emi_installments FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can insert own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can update own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can delete own liability_payments" ON public.liability_payments;

CREATE POLICY "Users can select own liability_payments" ON public.liability_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liability_payments" ON public.liability_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liability_payments" ON public.liability_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liability_payments" ON public.liability_payments FOR DELETE USING (auth.uid() = user_id);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.liabilities TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.emi_installments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.liability_payments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.expenses TO authenticated;

-- -----------------------------------------------------------------------------
-- record_liability_payment
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_liability_payment(
    p_payment_id UUID,
    p_liability_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_notes TEXT DEFAULT '',
    p_add_to_expense BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_creditor_name TEXT;
    v_liability_type TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_existing_payment RECORD;
    v_expense_id BIGINT;
    v_new_paid NUMERIC;
    v_new_remaining NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required';
    END IF;

    SELECT creditor_name, liability_type, COALESCE(total_amount, 0), COALESCE(paid_amount, 0)
    INTO v_creditor_name, v_liability_type, v_total_amount, v_current_paid
    FROM public.liabilities
    WHERE id = p_liability_id AND user_id = v_user_id;

    IF v_creditor_name IS NULL THEN
        RAISE EXCEPTION 'Liability not found or access denied';
    END IF;

    SELECT * INTO v_existing_payment
    FROM public.liability_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded safely.'
        );
    END IF;

    IF p_add_to_expense THEN
        v_expense_id := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;

        INSERT INTO public.expenses (
            id,
            user_id,
            date,
            category,
            description,
            amount,
            month,
            notes
        ) VALUES (
            v_expense_id,
            v_user_id,
            p_payment_date,
            v_liability_type || ' Repayment',
            'Repaid to: ' || v_creditor_name,
            p_amount,
            'Month 1',
            COALESCE(p_notes, '')
        );
    ELSE
        v_expense_id := NULL;
    END IF;

    INSERT INTO public.liability_payments (
        id,
        user_id,
        liability_id,
        payment_date,
        amount,
        payment_method,
        expense_id,
        notes
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_liability_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        v_expense_id,
        COALESCE(p_notes, '')
    );

    v_new_paid := v_current_paid + p_amount;
    v_new_remaining := GREATEST(0, v_total_amount - v_new_paid);

    IF v_new_paid >= v_total_amount THEN
        v_new_status := 'Paid Off';
    ELSE
        v_new_status := 'Active';
    END IF;

    UPDATE public.liabilities
    SET paid_amount = v_new_paid,
        remaining_amount = v_new_remaining,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_liability_id AND user_id = v_user_id;

    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'expense_id', v_expense_id,
        'new_paid', v_new_paid,
        'new_remaining', v_new_remaining,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.record_liability_payment(
    UUID,
    BIGINT,
    DATE,
    NUMERIC,
    TEXT,
    TEXT,
    BOOLEAN
) TO authenticated;

-- -----------------------------------------------------------------------------
-- record_emi_payment
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_emi_payment(
    p_payment_id UUID,
    p_liability_id BIGINT,
    p_installment_id UUID,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_notes TEXT DEFAULT '',
    p_add_to_expense BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_creditor_name TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_existing_payment RECORD;
    v_expense_id BIGINT;
    v_installment_expected NUMERIC;
    v_installment_paid NUMERIC;
    v_new_installment_paid NUMERIC;
    v_new_installment_status TEXT;
    v_new_paid NUMERIC;
    v_new_remaining NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required';
    END IF;

    SELECT creditor_name, COALESCE(total_amount, 0), COALESCE(paid_amount, 0)
    INTO v_creditor_name, v_total_amount, v_current_paid
    FROM public.liabilities
    WHERE id = p_liability_id AND user_id = v_user_id;

    IF v_creditor_name IS NULL THEN
        RAISE EXCEPTION 'Liability not found or access denied';
    END IF;

    SELECT expected_amount, COALESCE(paid_amount, 0)
    INTO v_installment_expected, v_installment_paid
    FROM public.emi_installments
    WHERE id = p_installment_id AND liability_id = p_liability_id AND user_id = v_user_id;

    IF v_installment_expected IS NULL THEN
        RAISE EXCEPTION 'EMI Installment not found or access denied';
    END IF;

    IF p_amount > (v_installment_expected - v_installment_paid) THEN
        RAISE EXCEPTION 'Payment amount exceeds remaining amount for this installment';
    END IF;

    SELECT * INTO v_existing_payment
    FROM public.liability_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded safely.'
        );
    END IF;

    IF p_add_to_expense THEN
        v_expense_id := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;

        INSERT INTO public.expenses (
            id,
            user_id,
            date,
            category,
            description,
            amount,
            month,
            notes
        ) VALUES (
            v_expense_id,
            v_user_id,
            p_payment_date,
            'EMI Repayment',
            'Repaid to: ' || v_creditor_name,
            p_amount,
            'Month 1',
            COALESCE(p_notes, '')
        );
    ELSE
        v_expense_id := NULL;
    END IF;

    INSERT INTO public.liability_payments (
        id,
        user_id,
        liability_id,
        emi_installment_id,
        payment_date,
        amount,
        payment_method,
        expense_id,
        notes
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_liability_id,
        p_installment_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        v_expense_id,
        COALESCE(p_notes, '')
    );

    v_new_installment_paid := v_installment_paid + p_amount;

    IF v_new_installment_paid >= v_installment_expected THEN
        v_new_installment_status := 'Paid';
    ELSE
        v_new_installment_status := 'Partial';
    END IF;

    UPDATE public.emi_installments
    SET paid_amount = v_new_installment_paid,
        status = v_new_installment_status,
        updated_at = NOW()
    WHERE id = p_installment_id AND user_id = v_user_id;

    v_new_paid := v_current_paid + p_amount;
    v_new_remaining := GREATEST(0, v_total_amount - v_new_paid);

    IF v_new_paid >= v_total_amount THEN
        v_new_status := 'Paid Off';
    ELSE
        v_new_status := 'Active';
    END IF;

    UPDATE public.liabilities
    SET paid_amount = v_new_paid,
        remaining_amount = v_new_remaining,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_liability_id AND user_id = v_user_id;

    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'expense_id', v_expense_id,
        'installment_status', v_new_installment_status,
        'new_paid', v_new_paid,
        'new_remaining', v_new_remaining,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.record_emi_payment(
    UUID,
    BIGINT,
    UUID,
    DATE,
    NUMERIC,
    TEXT,
    TEXT,
    BOOLEAN
) TO authenticated;

NOTIFY pgrst, 'reload schema';
