-- ====================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR PERSONAL BUSINESS MANAGEMENT APP
-- ====================================================================

-- 1. ENABLE EXTENSION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    target_income NUMERIC NOT NULL DEFAULT 100000,
    installment NUMERIC NOT NULL DEFAULT 80000,
    daily_outreach_target INT NOT NULL DEFAULT 10,
    currency TEXT NOT NULL DEFAULT '৳',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_settings UNIQUE(user_id)
);

-- 3. TASKS TABLE
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Sales',
    priority TEXT NOT NULL DEFAULT 'High',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    target_metric TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'NotStarted',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. CRM CLIENTS (LEADS) TABLE
CREATE TABLE IF NOT EXISTS public.crm_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    client_name TEXT NOT NULL,
    business_name TEXT NOT NULL,
    contact TEXT DEFAULT '',
    service TEXT DEFAULT '',
    quoted_price NUMERIC DEFAULT 0,
    advance NUMERIC DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'New',
    next_follow_up DATE NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. INCOME TABLE
CREATE TABLE IF NOT EXISTS public.income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    source TEXT NOT NULL,
    client_details TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    payment_type TEXT DEFAULT 'bKash',
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. EXPENSES TABLE
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. WEEKLY REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.weekly_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    week_title TEXT NOT NULL,
    outreach_count INT DEFAULT 0,
    replies_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    clients_won_count INT DEFAULT 0,
    new_income NUMERIC DEFAULT 0,
    main_achievement TEXT DEFAULT '',
    main_problem TEXT DEFAULT '',
    next_week_priority TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    delivery_time TEXT DEFAULT '',
    includes TEXT[] DEFAULT '{}',
    notes TEXT DEFAULT '',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. NINETY DAY PLAN TABLE
CREATE TABLE IF NOT EXISTS public.ninety_day_plan (
    id TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    month_title TEXT NOT NULL,
    target_income TEXT DEFAULT '',
    new_income_target TEXT DEFAULT '',
    focus TEXT DEFAULT '',
    weeks JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, user_id)
);

-- 10. SUBSCRIPTIONS TABLE (Current User Access State)
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'unpaid', -- 'unpaid', 'pending', 'active', 'expired', 'rejected'
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    starts_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_subscription UNIQUE(user_id)
);

-- 11. PAYMENT REQUESTS TABLE (Payment Submission & Renewal History)
CREATE TABLE IF NOT EXISTS public.payment_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    amount NUMERIC NOT NULL DEFAULT 500,
    payment_method TEXT NOT NULL, -- 'bKash', 'Nagad', 'Rocket'
    sender_number TEXT NOT NULL,
    trx_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ninety_day_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_requests ENABLE ROW LEVEL SECURITY;

-- SETTINGS POLICIES
DROP POLICY IF EXISTS "Users can select own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can insert own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can update own settings" ON public.settings;
CREATE POLICY "Users can select own settings" ON public.settings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own settings" ON public.settings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own settings" ON public.settings FOR UPDATE USING (auth.uid() = user_id);

-- TASKS POLICIES
DROP POLICY IF EXISTS "Users can select own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON public.tasks;
CREATE POLICY "Users can select own tasks" ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tasks" ON public.tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tasks" ON public.tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tasks" ON public.tasks FOR DELETE USING (auth.uid() = user_id);

-- CRM CLIENTS POLICIES
DROP POLICY IF EXISTS "Users can select own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can insert own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can update own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can delete own crm_clients" ON public.crm_clients;
CREATE POLICY "Users can select own crm_clients" ON public.crm_clients FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own crm_clients" ON public.crm_clients FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own crm_clients" ON public.crm_clients FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own crm_clients" ON public.crm_clients FOR DELETE USING (auth.uid() = user_id);

-- INCOME POLICIES
DROP POLICY IF EXISTS "Users can select own income" ON public.income;
DROP POLICY IF EXISTS "Users can insert own income" ON public.income;
DROP POLICY IF EXISTS "Users can update own income" ON public.income;
DROP POLICY IF EXISTS "Users can delete own income" ON public.income;
CREATE POLICY "Users can select own income" ON public.income FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own income" ON public.income FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own income" ON public.income FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own income" ON public.income FOR DELETE USING (auth.uid() = user_id);

-- EXPENSES POLICIES
DROP POLICY IF EXISTS "Users can select own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
CREATE POLICY "Users can select own expenses" ON public.expenses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own expenses" ON public.expenses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own expenses" ON public.expenses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own expenses" ON public.expenses FOR DELETE USING (auth.uid() = user_id);

-- WEEKLY REVIEWS POLICIES
DROP POLICY IF EXISTS "Users can select own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can insert own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can update own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can delete own weekly_reviews" ON public.weekly_reviews;
CREATE POLICY "Users can select own weekly_reviews" ON public.weekly_reviews FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own weekly_reviews" ON public.weekly_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own weekly_reviews" ON public.weekly_reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own weekly_reviews" ON public.weekly_reviews FOR DELETE USING (auth.uid() = user_id);

-- SERVICES POLICIES
DROP POLICY IF EXISTS "Users can select own services" ON public.services;
DROP POLICY IF EXISTS "Users can insert own services" ON public.services;
DROP POLICY IF EXISTS "Users can update own services" ON public.services;
DROP POLICY IF EXISTS "Users can delete own services" ON public.services;
CREATE POLICY "Users can select own services" ON public.services FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own services" ON public.services FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own services" ON public.services FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own services" ON public.services FOR DELETE USING (auth.uid() = user_id);

-- NINETY DAY PLAN POLICIES
DROP POLICY IF EXISTS "Users can select own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can insert own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can update own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can delete own ninety_day_plan" ON public.ninety_day_plan;
CREATE POLICY "Users can select own ninety_day_plan" ON public.ninety_day_plan FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own ninety_day_plan" ON public.ninety_day_plan FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ninety_day_plan" ON public.ninety_day_plan FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ninety_day_plan" ON public.ninety_day_plan FOR DELETE USING (auth.uid() = user_id);

-- SUBSCRIPTIONS POLICIES
DROP POLICY IF EXISTS "Users can view own subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can insert own initial subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can update own subscription to pending" ON public.subscriptions;
CREATE POLICY "Users can view own subscription" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = user_id OR (auth.jwt() ->> 'email') = 'fuwaraahmed@gmail.com');

CREATE POLICY "Users can insert own initial subscription" 
    ON public.subscriptions FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own subscription to pending" 
    ON public.subscriptions FOR UPDATE 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- PAYMENT REQUESTS POLICIES
DROP POLICY IF EXISTS "Users can view own payment requests" ON public.payment_requests;
DROP POLICY IF EXISTS "Users can submit own payment requests" ON public.payment_requests;
CREATE POLICY "Users can view own payment requests" 
    ON public.payment_requests FOR SELECT 
    USING (auth.uid() = user_id OR (auth.jwt() ->> 'email') = 'fuwaraahmed@gmail.com');

CREATE POLICY "Users can submit own payment requests" 
    ON public.payment_requests FOR INSERT 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- ====================================================================
-- SERVER-SIDE ADMIN RPC APPROVAL FUNCTIONS (SECURITY DEFINER)
-- ====================================================================

-- 1. FUNCTION TO APPROVE PAYMENT REQUEST
CREATE OR REPLACE FUNCTION public.approve_payment_request(request_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    req RECORD;
    caller_email TEXT;
BEGIN
    caller_email := auth.jwt() ->> 'email';
    
    IF caller_email IS NULL OR caller_email != 'fuwaraahmed@gmail.com' THEN
        RAISE EXCEPTION 'Unauthorized: Only the system administrator can approve payment requests.';
    END IF;

    SELECT * INTO req FROM public.payment_requests WHERE id = request_id AND status = 'pending';
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'approved', updated_at = NOW() 
    WHERE id = request_id;

    INSERT INTO public.subscriptions (user_id, user_email, status, plan_name, starts_at, expires_at, updated_at)
    VALUES (req.user_id, req.user_email, 'active', req.plan_name, NOW(), NOW() + INTERVAL '30 days', NOW())
    ON CONFLICT (user_id) 
    DO UPDATE SET 
        status = 'active',
        plan_name = EXCLUDED.plan_name,
        starts_at = NOW(),
        expires_at = NOW() + INTERVAL '30 days',
        updated_at = NOW();

    RETURN jsonb_build_object('success', true, 'message', 'Payment request approved successfully.');
END;
$$;

-- 2. FUNCTION TO REJECT PAYMENT REQUEST
CREATE OR REPLACE FUNCTION public.reject_payment_request(request_id UUID, rejection_reason TEXT DEFAULT '')
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    req RECORD;
    caller_email TEXT;
BEGIN
    caller_email := auth.jwt() ->> 'email';
    
    IF caller_email IS NULL OR caller_email != 'fuwaraahmed@gmail.com' THEN
        RAISE EXCEPTION 'Unauthorized: Only the system administrator can reject payment requests.';
    END IF;

    SELECT * INTO req FROM public.payment_requests WHERE id = request_id AND status = 'pending';
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'rejected', admin_notes = rejection_reason, updated_at = NOW() 
    WHERE id = request_id;

    UPDATE public.subscriptions 
    SET status = 'rejected', updated_at = NOW() 
    WHERE user_id = req.user_id AND status != 'active';

    RETURN jsonb_build_object('success', true, 'message', 'Payment request rejected.');
END;
$$;
