-- ====================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR PERSONAL BUSINESS MANAGEMENT APP
-- ====================================================================

-- 1. ENABLE EXTENSION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    target_income NUMERIC NOT NULL DEFAULT 100000,
    installment NUMERIC NOT NULL DEFAULT 80000,
    daily_outreach_target INT NOT NULL DEFAULT 10,
    currency TEXT NOT NULL DEFAULT '৳',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_settings UNIQUE(user_id)
);

-- 3. TASKS TABLE
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Sales',
    priority TEXT NOT NULL DEFAULT 'High',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    target_metric TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'NotStarted',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. CRM CLIENTS (LEADS) TABLE
CREATE TABLE IF NOT EXISTS public.crm_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    client_name TEXT NOT NULL,
    business_name TEXT NOT NULL,
    contact TEXT DEFAULT '',
    service TEXT DEFAULT '',
    quoted_price NUMERIC DEFAULT 0,
    advance NUMERIC DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'New',
    next_follow_up DATE NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. INCOME TABLE
CREATE TABLE IF NOT EXISTS public.income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    source TEXT NOT NULL,
    client_details TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    payment_type TEXT DEFAULT 'bKash',
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. EXPENSES TABLE
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. WEEKLY REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.weekly_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    week_title TEXT NOT NULL,
    outreach_count INT DEFAULT 0,
    replies_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    clients_won_count INT DEFAULT 0,
    new_income NUMERIC DEFAULT 0,
    main_achievement TEXT DEFAULT '',
    main_problem TEXT DEFAULT '',
    next_week_priority TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    delivery_time TEXT DEFAULT '',
    includes TEXT[] DEFAULT '{}',
    notes TEXT DEFAULT '',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. NINETY DAY PLAN TABLE
CREATE TABLE IF NOT EXISTS public.ninety_day_plan (
    id TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    month_title TEXT NOT NULL,
    target_income TEXT DEFAULT '',
    new_income_target TEXT DEFAULT '',
    focus TEXT DEFAULT '',
    weeks JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, user_id)
);

-- 10. SUBSCRIPTIONS TABLE (Current User Access State)
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'unpaid', -- 'unpaid', 'pending', 'active', 'expired', 'rejected'
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    billing_cycle TEXT NOT NULL DEFAULT 'monthly',
    starts_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_subscription UNIQUE(user_id)
);

-- Ensure billing_cycle and plan_id exists for additive migration
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS billing_cycle TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS plan_id TEXT;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_plan_id TEXT;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_starts_at TIMESTAMPTZ;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMPTZ;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_ended_at TIMESTAMPTZ;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS trial_note TEXT;

-- 11. PAYMENT REQUESTS TABLE (Payment Submission & Renewal History)
CREATE TABLE IF NOT EXISTS public.payment_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    amount NUMERIC NOT NULL DEFAULT 500,
    payment_method TEXT NOT NULL, -- 'bKash', 'Nagad', 'Rocket'
    sender_number TEXT NOT NULL,
    trx_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure plan_id exists for additive migration
ALTER TABLE public.payment_requests ADD COLUMN IF NOT EXISTS plan_id TEXT;

-- 12. TRIAL HISTORY TABLE (Append-Only Free Trial Audit History)
CREATE TABLE IF NOT EXISTS public.trial_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    action TEXT NOT NULL CHECK (action IN ('START', 'EXTEND', 'SET_DATE', 'END', 'RESET', 'CONVERTED_TO_PAID')),
    days_added INTEGER DEFAULT 0,
    previous_end_at TIMESTAMPTZ,
    new_end_at TIMESTAMPTZ,
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trial_history_user_created 
    ON public.trial_history(user_id, created_at DESC);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ninety_day_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trial_history ENABLE ROW LEVEL SECURITY;

-- SETTINGS POLICIES
DROP POLICY IF EXISTS "Users can select own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can insert own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can update own settings" ON public.settings;
CREATE POLICY "Users can select own settings" ON public.settings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own settings" ON public.settings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own settings" ON public.settings FOR UPDATE USING (auth.uid() = user_id);

-- TASKS POLICIES
DROP POLICY IF EXISTS "Users can select own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON public.tasks;
CREATE POLICY "Users can select own tasks" ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tasks" ON public.tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tasks" ON public.tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tasks" ON public.tasks FOR DELETE USING (auth.uid() = user_id);

-- CRM CLIENTS POLICIES
DROP POLICY IF EXISTS "Users can select own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can insert own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can update own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can delete own crm_clients" ON public.crm_clients;
CREATE POLICY "Users can select own crm_clients" ON public.crm_clients FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own crm_clients" ON public.crm_clients FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own crm_clients" ON public.crm_clients FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own crm_clients" ON public.crm_clients FOR DELETE USING (auth.uid() = user_id);

-- INCOME POLICIES
DROP POLICY IF EXISTS "Users can select own income" ON public.income;
DROP POLICY IF EXISTS "Users can insert own income" ON public.income;
DROP POLICY IF EXISTS "Users can update own income" ON public.income;
DROP POLICY IF EXISTS "Users can delete own income" ON public.income;
CREATE POLICY "Users can select own income" ON public.income FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own income" ON public.income FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own income" ON public.income FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own income" ON public.income FOR DELETE USING (auth.uid() = user_id);

-- EXPENSES POLICIES
DROP POLICY IF EXISTS "Users can select own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
CREATE POLICY "Users can select own expenses" ON public.expenses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own expenses" ON public.expenses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own expenses" ON public.expenses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own expenses" ON public.expenses FOR DELETE USING (auth.uid() = user_id);

-- WEEKLY REVIEWS POLICIES
DROP POLICY IF EXISTS "Users can select own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can insert own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can update own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can delete own weekly_reviews" ON public.weekly_reviews;
CREATE POLICY "Users can select own weekly_reviews" ON public.weekly_reviews FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own weekly_reviews" ON public.weekly_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own weekly_reviews" ON public.weekly_reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own weekly_reviews" ON public.weekly_reviews FOR DELETE USING (auth.uid() = user_id);

-- SERVICES POLICIES
DROP POLICY IF EXISTS "Users can select own services" ON public.services;
DROP POLICY IF EXISTS "Users can insert own services" ON public.services;
DROP POLICY IF EXISTS "Users can update own services" ON public.services;
DROP POLICY IF EXISTS "Users can delete own services" ON public.services;
CREATE POLICY "Users can select own services" ON public.services FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own services" ON public.services FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own services" ON public.services FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own services" ON public.services FOR DELETE USING (auth.uid() = user_id);

-- NINETY DAY PLAN POLICIES
DROP POLICY IF EXISTS "Users can select own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can insert own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can update own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can delete own ninety_day_plan" ON public.ninety_day_plan;
CREATE POLICY "Users can select own ninety_day_plan" ON public.ninety_day_plan FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own ninety_day_plan" ON public.ninety_day_plan FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ninety_day_plan" ON public.ninety_day_plan FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ninety_day_plan" ON public.ninety_day_plan FOR DELETE USING (auth.uid() = user_id);

-- ====================================================================
-- USER ROLES & ADMINISTRATIVE AUTHORIZATION
-- ====================================================================

CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_role UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- SECURITY DEFINER function to verify if a user has an admin role
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF p_user_id IS NULL THEN
        RETURN FALSE;
    END IF;
    RETURN EXISTS (
        SELECT 1 
        FROM public.user_roles 
        WHERE user_id = p_user_id 
          AND role = 'admin'
    );
END;
$$;

-- RLS Policy for user_roles table
DROP POLICY IF EXISTS "Users can view own role or admin can view all" ON public.user_roles;
CREATE POLICY "Users can view own role or admin can view all" 
    ON public.user_roles FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

-- Insert initial admin role for existing admin user if present in auth.users
INSERT INTO public.user_roles (user_id, role)
SELECT id, 'admin'
FROM auth.users
WHERE email = 'fuwaraahmed@gmail.com'
ON CONFLICT (user_id, role) DO NOTHING;

-- SUBSCRIPTIONS POLICIES
DROP POLICY IF EXISTS "Users can view own subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can insert own initial subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can update own subscription to pending" ON public.subscriptions;
CREATE POLICY "Users can view own subscription" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

CREATE POLICY "Users can insert own initial subscription" 
    ON public.subscriptions FOR INSERT 
    TO authenticated
    WITH CHECK (
        auth.uid() = user_id 
        AND status IN ('unpaid', 'pending')
        AND trial_starts_at IS NULL
        AND trial_ends_at IS NULL
        AND trial_ended_at IS NULL
        AND trial_plan_id IS NULL
        AND trial_note IS NULL
    );

CREATE POLICY "Users can update own subscription to pending" 
    ON public.subscriptions FOR UPDATE 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- TRIAL HISTORY POLICIES (Append-Only Audit Log)
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.trial_history FROM PUBLIC, anon, authenticated;
DROP POLICY IF EXISTS "Users can view own trial history or admin can view all" ON public.trial_history;
CREATE POLICY "Users can view own trial history or admin can view all" 
    ON public.trial_history FOR SELECT 
    TO authenticated
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));
GRANT SELECT ON public.trial_history TO authenticated;

-- TRIGGER TO PREVENT CLIENT-SIDE MODIFICATION OF TRIAL COLUMNS ON UPDATE
CREATE OR REPLACE FUNCTION public.protect_subscription_trial_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF public.is_admin(auth.uid()) THEN
        RETURN NEW;
    END IF;

    IF (NEW.trial_plan_id IS DISTINCT FROM OLD.trial_plan_id) OR
       (NEW.trial_starts_at IS DISTINCT FROM OLD.trial_starts_at) OR
       (NEW.trial_ends_at IS DISTINCT FROM OLD.trial_ends_at) OR
       (NEW.trial_ended_at IS DISTINCT FROM OLD.trial_ended_at) OR
       (NEW.trial_note IS DISTINCT FROM OLD.trial_note) THEN
        RAISE EXCEPTION 'Unauthorized: Trial fields cannot be modified by standard users.';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_subscription_trial_fields ON public.subscriptions;
CREATE TRIGGER trg_protect_subscription_trial_fields
    BEFORE UPDATE ON public.subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION public.protect_subscription_trial_fields();

-- PAYMENT REQUESTS POLICIES
DROP POLICY IF EXISTS "Users can view own payment requests" ON public.payment_requests;
DROP POLICY IF EXISTS "Users can submit own payment requests" ON public.payment_requests;
CREATE POLICY "Users can view own payment requests" 
    ON public.payment_requests FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

CREATE POLICY "Users can submit own payment requests" 
    ON public.payment_requests FOR INSERT 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- ====================================================================
-- SERVER-SIDE ADMIN & TRIAL RPC FUNCTIONS (SECURITY DEFINER)
-- ====================================================================

-- 1. FUNCTION TO START SELF-SERVICE 14-DAY TRIAL
CREATE OR REPLACE FUNCTION public.start_self_service_trial()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_user_email TEXT;
    v_sub RECORD;
    v_new_end TIMESTAMPTZ;
    v_has_previous_trial BOOLEAN;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required to start a trial.';
    END IF;

    SELECT email INTO v_user_email FROM auth.users WHERE id = v_user_id;
    IF v_user_email IS NULL THEN
        RAISE EXCEPTION 'User account not found.';
    END IF;

    SELECT * INTO v_sub 
    FROM public.subscriptions 
    WHERE user_id = v_user_id 
    FOR UPDATE;

    IF v_sub IS NOT NULL AND v_sub.status = 'active' AND v_sub.expires_at IS NOT NULL AND v_sub.expires_at > NOW() THEN
        RETURN jsonb_build_object(
            'success', false, 
            'message', 'আপনার ইতিমধ্যে একটি সক্রিয় পেইড সাবস্ক্রিপশন চালু রয়েছে।'
        );
    END IF;

    IF v_sub IS NOT NULL AND v_sub.trial_ends_at IS NOT NULL AND v_sub.trial_ends_at > NOW() AND v_sub.trial_ended_at IS NULL THEN
        RETURN jsonb_build_object(
            'success', false, 
            'message', 'আপনার ফ্রি ট্রায়াল ইতিমধ্যে সক্রিয় রয়েছে।'
        );
    END IF;

    v_has_previous_trial := (
        (v_sub IS NOT NULL AND v_sub.trial_starts_at IS NOT NULL) OR
        EXISTS (SELECT 1 FROM public.trial_history WHERE user_id = v_user_id)
    );

    IF v_has_previous_trial THEN
        RETURN jsonb_build_object(
            'success', false, 
            'already_used', true,
            'message', 'আপনি ইতিমধ্যে আপনার ফ্রি ট্রায়াল ব্যবহার করেছেন। সেবা চালু রাখতে সাবস্ক্রাইব করুন।'
        );
    END IF;

    v_new_end := NOW() + INTERVAL '14 days';

    IF v_sub IS NULL THEN
        INSERT INTO public.subscriptions (
            user_id,
            user_email,
            status,
            plan_id,
            plan_name,
            billing_cycle,
            starts_at,
            expires_at,
            trial_plan_id,
            trial_starts_at,
            trial_ends_at,
            trial_ended_at,
            trial_note,
            created_at,
            updated_at
        ) VALUES (
            v_user_id,
            v_user_email,
            'unpaid',
            NULL,
            'Starter',
            'monthly',
            NULL,
            NULL,
            'starter',
            NOW(),
            v_new_end,
            NULL,
            'Self-service 14-day free trial',
            NOW(),
            NOW()
        );
    ELSE
        UPDATE public.subscriptions
        SET trial_plan_id = 'starter',
            trial_starts_at = NOW(),
            trial_ends_at = v_new_end,
            trial_ended_at = NULL,
            trial_note = 'Self-service 14-day free trial',
            updated_at = NOW()
        WHERE user_id = v_user_id;
    END IF;

    INSERT INTO public.trial_history (
        user_id,
        admin_id,
        action,
        days_added,
        previous_end_at,
        new_end_at,
        note
    ) VALUES (
        v_user_id,
        v_user_id,
        'START',
        14,
        NULL,
        v_new_end,
        'Self-service 14-day trial started by user'
    );

    RETURN jsonb_build_object(
        'success', true, 
        'trial_ends_at', v_new_end,
        'message', '১৪ দিনের ফ্রি ট্রায়াল সফলভাবে চালু হয়েছে!'
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.start_self_service_trial() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.start_self_service_trial() FROM anon;
GRANT EXECUTE ON FUNCTION public.start_self_service_trial() TO authenticated;

-- 2. FUNCTION TO MANAGE USER TRIAL (ADMIN ONLY)
CREATE OR REPLACE FUNCTION public.manage_user_trial(
    p_user_id UUID,
    p_action TEXT,
    p_days INT DEFAULT NULL,
    p_target_date TIMESTAMPTZ DEFAULT NULL,
    p_plan_id TEXT DEFAULT 'starter',
    p_reason TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_admin_id UUID;
    v_sub RECORD;
    v_user_email TEXT;
    v_new_end TIMESTAMPTZ;
    v_prev_end TIMESTAMPTZ;
    v_clean_plan TEXT;
    v_is_paid_active BOOLEAN;
    v_is_trial_active BOOLEAN;
BEGIN
    v_admin_id := auth.uid();
    IF v_admin_id IS NULL OR NOT public.is_admin(v_admin_id) THEN
        RAISE EXCEPTION 'Unauthorized: Only system administrators can manage trials.';
    END IF;

    SELECT email INTO v_user_email FROM auth.users WHERE id = p_user_id;
    IF v_user_email IS NULL THEN
        RAISE EXCEPTION 'User not found in system.';
    END IF;

    IF p_action NOT IN ('START', 'EXTEND', 'SET_DATE', 'END', 'RESET') THEN
        RAISE EXCEPTION 'Invalid trial action: %', p_action;
    END IF;

    v_clean_plan := COALESCE(NULLIF(trim(p_plan_id), ''), 'starter');
    IF v_clean_plan NOT IN ('starter', 'monthly_pro', 'pro_business', 'agency') THEN
        RAISE EXCEPTION 'Invalid plan ID: %', p_plan_id;
    END IF;

    SELECT * INTO v_sub 
    FROM public.subscriptions 
    WHERE user_id = p_user_id 
    FOR UPDATE;

    v_is_paid_active := (v_sub IS NOT NULL AND v_sub.status = 'active' AND v_sub.expires_at IS NOT NULL AND v_sub.expires_at > NOW());
    v_is_trial_active := (v_sub IS NOT NULL AND v_sub.trial_ends_at IS NOT NULL AND v_sub.trial_ends_at > NOW() AND v_sub.trial_ended_at IS NULL);
    v_prev_end := v_sub.trial_ends_at;

    IF v_is_paid_active AND p_action IN ('START', 'EXTEND', 'SET_DATE') THEN
        RAISE EXCEPTION 'User already has an active paid subscription until %. Trial actions are blocked.', to_char(v_sub.expires_at, 'YYYY-MM-DD HH24:MI:SS');
    END IF;

    IF p_action = 'START' THEN
        IF v_is_trial_active THEN
            RAISE EXCEPTION 'User already has an active trial until %. Use Extend instead.', to_char(v_sub.trial_ends_at, 'YYYY-MM-DD HH24:MI:SS');
        END IF;

        IF p_days IS NULL OR p_days < 1 OR p_days > 90 THEN
            RAISE EXCEPTION 'Trial duration must be between 1 and 90 days.';
        END IF;

        v_new_end := NOW() + (p_days || ' days')::INTERVAL;

        IF v_sub IS NULL THEN
            INSERT INTO public.subscriptions (
                user_id,
                user_email,
                status,
                plan_id,
                plan_name,
                billing_cycle,
                starts_at,
                expires_at,
                trial_plan_id,
                trial_starts_at,
                trial_ends_at,
                trial_ended_at,
                trial_note,
                created_at,
                updated_at
            ) VALUES (
                p_user_id,
                v_user_email,
                'unpaid',
                NULL,
                'Starter',
                'monthly',
                NULL,
                NULL,
                v_clean_plan,
                NOW(),
                v_new_end,
                NULL,
                COALESCE(p_reason, ''),
                NOW(),
                NOW()
            );
        ELSE
            UPDATE public.subscriptions
            SET trial_plan_id = v_clean_plan,
                trial_starts_at = NOW(),
                trial_ends_at = v_new_end,
                trial_ended_at = NULL,
                trial_note = COALESCE(p_reason, ''),
                updated_at = NOW()
            WHERE user_id = p_user_id;
        END IF;

        INSERT INTO public.trial_history (
            user_id, admin_id, action, days_added, previous_end_at, new_end_at, note
        ) VALUES (
            p_user_id, v_admin_id, 'START', p_days, v_prev_end, v_new_end, COALESCE(p_reason, '')
        );

        RETURN jsonb_build_object(
            'success', true,
            'action', 'START',
            'trial_ends_at', v_new_end,
            'message', 'Free trial started successfully.'
        );

    ELSIF p_action = 'EXTEND' THEN
        IF v_sub IS NULL THEN
            RAISE EXCEPTION 'No subscription record found. Start a trial first.';
        END IF;

        IF p_days IS NULL OR p_days < 1 OR p_days > 90 THEN
            RAISE EXCEPTION 'Extension days must be between 1 and 90 days.';
        END IF;

        IF v_is_trial_active THEN
            v_new_end := v_sub.trial_ends_at + (p_days || ' days')::INTERVAL;
        ELSE
            v_new_end := NOW() + (p_days || ' days')::INTERVAL;
        END IF;

        UPDATE public.subscriptions
        SET trial_ends_at = v_new_end,
            trial_ended_at = NULL,
            updated_at = NOW()
        WHERE user_id = p_user_id;

        INSERT INTO public.trial_history (
            user_id, admin_id, action, days_added, previous_end_at, new_end_at, note
        ) VALUES (
            p_user_id, v_admin_id, 'EXTEND', p_days, v_prev_end, v_new_end, COALESCE(p_reason, '')
        );

        RETURN jsonb_build_object(
            'success', true,
            'action', 'EXTEND',
            'trial_ends_at', v_new_end,
            'message', 'Trial extended successfully.'
        );

    ELSIF p_action = 'SET_DATE' THEN
        IF v_sub IS NULL THEN
            RAISE EXCEPTION 'No subscription record found. Start a trial first.';
        END IF;

        IF p_target_date IS NULL OR p_target_date <= NOW() THEN
            RAISE EXCEPTION 'Target trial end date must be strictly in the future.';
        END IF;

        IF p_target_date > (NOW() + INTERVAL '365 days') THEN
            RAISE EXCEPTION 'Target trial end date cannot exceed 365 days from now.';
        END IF;

        IF v_prev_end IS NOT NULL AND p_target_date = v_prev_end THEN
            RAISE EXCEPTION 'Target date is identical to the current end date.';
        END IF;

        v_new_end := p_target_date;

        UPDATE public.subscriptions
        SET trial_ends_at = v_new_end,
            trial_ended_at = NULL,
            updated_at = NOW()
        WHERE user_id = p_user_id;

        INSERT INTO public.trial_history (
            user_id, admin_id, action, days_added, previous_end_at, new_end_at, note
        ) VALUES (
            p_user_id, v_admin_id, 'SET_DATE', 0, v_prev_end, v_new_end, COALESCE(p_reason, '')
        );

        RETURN jsonb_build_object(
            'success', true,
            'action', 'SET_DATE',
            'trial_ends_at', v_new_end,
            'message', 'Trial end date updated successfully.'
        );

    ELSIF p_action = 'END' THEN
        IF v_sub IS NULL THEN
            RAISE EXCEPTION 'No subscription record found.';
        END IF;

        IF v_sub.trial_ended_at IS NOT NULL THEN
            RETURN jsonb_build_object(
                'success', true,
                'action', 'END',
                'message', 'Trial was already ended.'
            );
        END IF;

        UPDATE public.subscriptions
        SET trial_ended_at = NOW(),
            updated_at = NOW()
        WHERE user_id = p_user_id;

        INSERT INTO public.trial_history (
            user_id, admin_id, action, days_added, previous_end_at, new_end_at, note
        ) VALUES (
            p_user_id, v_admin_id, 'END', 0, v_prev_end, NOW(), COALESCE(p_reason, '')
        );

        RETURN jsonb_build_object(
            'success', true,
            'action', 'END',
            'message', 'Trial ended successfully.'
        );

    ELSIF p_action = 'RESET' THEN
        IF v_sub IS NULL THEN
            RAISE EXCEPTION 'No subscription record found.';
        END IF;

        IF p_reason IS NULL OR char_length(trim(p_reason)) < 5 THEN
            RAISE EXCEPTION 'A mandatory audit reason of at least 5 characters is required to reset a trial.';
        END IF;

        UPDATE public.subscriptions
        SET trial_plan_id = NULL,
            trial_starts_at = NULL,
            trial_ends_at = NULL,
            trial_ended_at = NOW(),
            trial_note = trim(p_reason),
            updated_at = NOW()
        WHERE user_id = p_user_id;

        INSERT INTO public.trial_history (
            user_id, admin_id, action, days_added, previous_end_at, new_end_at, note
        ) VALUES (
            p_user_id, v_admin_id, 'RESET', 0, v_prev_end, NULL, trim(p_reason)
        );

        RETURN jsonb_build_object(
            'success', true,
            'action', 'RESET',
            'message', 'Trial state reset successfully.'
        );
    END IF;

    RETURN jsonb_build_object('success', false, 'message', 'Unhandled trial action.');
END;
$$;

REVOKE EXECUTE ON FUNCTION public.manage_user_trial(UUID, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.manage_user_trial(UUID, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT) FROM anon;
GRANT EXECUTE ON FUNCTION public.manage_user_trial(UUID, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT) TO authenticated;

-- 3. FUNCTION TO APPROVE PAYMENT REQUEST (WITH SMART RENEWAL & TRIAL CONVERSION)
CREATE OR REPLACE FUNCTION public.approve_payment_request(request_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    req RECORD;
    v_existing_sub RECORD;
    v_starts_at TIMESTAMPTZ;
    v_expires_at TIMESTAMPTZ;
    v_admin_id UUID;
    v_had_active_trial BOOLEAN;
BEGIN
    v_admin_id := auth.uid();
    IF v_admin_id IS NULL OR NOT public.is_admin(v_admin_id) THEN
        RAISE EXCEPTION 'Unauthorized: Only system administrators can approve payment requests.';
    END IF;

    -- 1. Fetch & lock pending payment request
    SELECT * INTO req 
    FROM public.payment_requests 
    WHERE id = request_id AND status = 'pending'
    FOR UPDATE;
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'approved', updated_at = NOW() 
    WHERE id = request_id;

    -- 2. Fetch & lock existing subscription for smart renewal & trial conversion
    SELECT * INTO v_existing_sub 
    FROM public.subscriptions 
    WHERE user_id = req.user_id
    FOR UPDATE;

    -- Smart Renewal calculation for paid subscription
    IF v_existing_sub IS NOT NULL AND v_existing_sub.status = 'active' AND v_existing_sub.expires_at > NOW() THEN
        v_starts_at := v_existing_sub.starts_at;
        v_expires_at := v_existing_sub.expires_at + INTERVAL '1 month';
    ELSE
        v_starts_at := NOW();
        v_expires_at := NOW() + INTERVAL '1 month';
    END IF;

    -- Check if user currently has an active trial
    v_had_active_trial := (
        v_existing_sub IS NOT NULL 
        AND v_existing_sub.trial_ends_at IS NOT NULL 
        AND v_existing_sub.trial_ends_at > NOW() 
        AND v_existing_sub.trial_ended_at IS NULL
    );

    -- 3. Upsert paid subscription state & conclude active trial if present
    INSERT INTO public.subscriptions (
        user_id, 
        user_email, 
        status, 
        plan_id, 
        plan_name, 
        billing_cycle, 
        starts_at, 
        expires_at, 
        trial_ended_at,
        updated_at
    ) VALUES (
        req.user_id, 
        req.user_email, 
        'active', 
        req.plan_id, 
        req.plan_name, 
        'monthly', 
        v_starts_at, 
        v_expires_at, 
        CASE WHEN v_had_active_trial THEN NOW() ELSE NULL END,
        NOW()
    )
    ON CONFLICT (user_id) 
    DO UPDATE SET 
        status = 'active',
        plan_id = EXCLUDED.plan_id,
        plan_name = EXCLUDED.plan_name,
        billing_cycle = 'monthly',
        starts_at = v_starts_at,
        expires_at = v_expires_at,
        trial_ended_at = CASE 
            WHEN v_had_active_trial THEN NOW() 
            ELSE public.subscriptions.trial_ended_at 
        END,
        updated_at = NOW();

    -- 4. If trial was active, record immutable CONVERTED_TO_PAID audit event
    IF v_had_active_trial THEN
        INSERT INTO public.trial_history (
            user_id,
            admin_id,
            action,
            days_added,
            previous_end_at,
            new_end_at,
            note
        ) VALUES (
            req.user_id,
            v_admin_id,
            'CONVERTED_TO_PAID',
            0,
            v_existing_sub.trial_ends_at,
            NOW(),
            'Trial concluded automatically upon payment request approval.'
        );
    END IF;

    RETURN jsonb_build_object(
        'success', true, 
        'converted_from_trial', v_had_active_trial,
        'message', 'Payment request approved successfully.'
    );
END;
$$;


-- 2. FUNCTION TO REJECT PAYMENT REQUEST
CREATE OR REPLACE FUNCTION public.reject_payment_request(request_id UUID, rejection_reason TEXT DEFAULT '')
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    req RECORD;
BEGIN
    IF NOT public.is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Unauthorized: Only system administrators can reject payment requests.';
    END IF;

    SELECT * INTO req FROM public.payment_requests WHERE id = request_id AND status = 'pending';
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'rejected', admin_notes = rejection_reason, updated_at = NOW() 
    WHERE id = request_id;

    UPDATE public.subscriptions 
    SET status = 'rejected', updated_at = NOW() 
    WHERE user_id = req.user_id AND status != 'active';

    RETURN jsonb_build_object('success', true, 'message', 'Payment request rejected.');
END;
$$;

-- ====================================================================
-- TUITION MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 12. TUITION STUDENTS TABLE
CREATE TABLE IF NOT EXISTS public.tuition_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    student_name TEXT NOT NULL,
    guardian_name TEXT DEFAULT '',
    mobile TEXT DEFAULT '',
    class_name TEXT DEFAULT '',
    batch TEXT DEFAULT '',
    monthly_fee NUMERIC NOT NULL CHECK (monthly_fee > 0),
    joining_date DATE NOT NULL DEFAULT CURRENT_DATE,
    billing_start_month TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Left', 'Inactive')),
    leaving_date DATE NULL,
    leaving_reason TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. TUITION PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.tuition_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    student_id BIGINT NOT NULL REFERENCES public.tuition_students(id) ON DELETE RESTRICT,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_month TEXT NOT NULL CHECK (payment_month ~ '^\d{4}-(0[1-9]|1[0-2])$'), -- Stored as 'YYYY-MM' (e.g. '2026-09')
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    note TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_student_monthly_payment UNIQUE (user_id, student_id, payment_month)
);

-- INDEXES FOR FAST SEARCH AND LOOKUP
CREATE INDEX IF NOT EXISTS idx_tuition_students_user_id ON public.tuition_students(user_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_user_id ON public.tuition_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_student_id ON public.tuition_payments(student_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_month ON public.tuition_payments(payment_month);

-- RLS ENABLMENT
ALTER TABLE public.tuition_students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tuition_payments ENABLE ROW LEVEL SECURITY;

-- TUITION STUDENTS POLICIES
DROP POLICY IF EXISTS "Users can select own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can insert own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can update own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can delete own tuition_students" ON public.tuition_students;

CREATE POLICY "Users can select own tuition_students" ON public.tuition_students FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tuition_students" ON public.tuition_students FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tuition_students" ON public.tuition_students FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tuition_students" ON public.tuition_students FOR DELETE USING (auth.uid() = user_id);

-- TUITION PAYMENTS POLICIES
DROP POLICY IF EXISTS "Users can select own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can insert own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can update own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can delete own tuition_payments" ON public.tuition_payments;

CREATE POLICY "Users can select own tuition_payments" ON public.tuition_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tuition_payments" ON public.tuition_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tuition_payments" ON public.tuition_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tuition_payments" ON public.tuition_payments FOR DELETE USING (auth.uid() = user_id);

-- ====================================================================
-- ATOMIC POSTGRESQL RPC FOR TUITION PAYMENT & INCOME CREATION
-- ====================================================================
CREATE OR REPLACE FUNCTION public.record_tuition_payment(
    p_student_id BIGINT,
    p_payment_date DATE,
    p_payment_month TEXT,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_student_name TEXT;
    v_class_name TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_payment_id BIGINT;
    v_result JSONB;
BEGIN
    -- 1. Verify user authentication
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input values
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_month IS NULL OR p_payment_month !~ '^\d{4}-(0[1-9]|1[0-2])$' THEN
        RAISE EXCEPTION 'Invalid payment month format. Must be YYYY-MM (e.g. 2026-09)';
    END IF;

    -- 3. Verify student ownership and fetch student details
    SELECT student_name, class_name
    INTO v_student_name, v_class_name
    FROM public.tuition_students
    WHERE id = p_student_id AND user_id = v_user_id;

    IF v_student_name IS NULL THEN
        RAISE EXCEPTION 'Student not found or access denied';
    END IF;

    -- Format client_details cleanly without trailing hyphen when class_name is empty
    IF v_class_name IS NOT NULL AND length(trim(v_class_name)) > 0 THEN
        v_client_details := v_student_name || ' - ' || trim(v_class_name);
    ELSE
        v_client_details := v_student_name;
    END IF;

    -- 4. Check duplicate monthly payment
    IF EXISTS (
        SELECT 1 FROM public.tuition_payments
        WHERE user_id = v_user_id
          AND student_id = p_student_id
          AND payment_month = p_payment_month
    ) THEN
        RAISE EXCEPTION 'A payment for month % already exists for this student', p_payment_month;
    END IF;

    -- 5. Create Income record
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes
    ) VALUES (
        v_user_id,
        p_payment_date,
        'Tuition',
        v_client_details,
        p_amount,
        p_payment_method,
        p_payment_month,
        COALESCE(p_note, '')
    )
    RETURNING id INTO v_income_id;

    -- 6. Create Tuition Payment record linked to Income
    INSERT INTO public.tuition_payments (
        user_id,
        student_id,
        payment_date,
        payment_month,
        amount,
        payment_method,
        note,
        income_id
    ) VALUES (
        v_user_id,
        p_student_id,
        p_payment_date,
        p_payment_month,
        p_amount,
        p_payment_method,
        COALESCE(p_note, ''),
        v_income_id
    )
    RETURNING id INTO v_payment_id;

    -- 7. Build and return combined result JSON
    SELECT jsonb_build_object(
        'success', true,
        'payment_id', v_payment_id,
        'income_id', v_income_id,
        'student_id', p_student_id,
        'amount', p_amount,
        'payment_month', p_payment_month,
        'payment_date', p_payment_date,
        'payment_method', p_payment_method,
        'note', p_note
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- CRM PAYMENT MODULE SCHEMA, UNIQUE CONSTRAINT & ATOMIC RPC
-- ====================================================================

-- 14. CRM PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.crm_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    crm_client_id BIGINT NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'bKash',
    notes TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ADD UNIQUE crm_payment_id TO INCOME TABLE FOR DATABASE-LEVEL IDEMPOTENCY
ALTER TABLE public.income ADD COLUMN IF NOT EXISTS crm_payment_id UUID UNIQUE NULL REFERENCES public.crm_payments(id) ON DELETE SET NULL;

-- INDEXES FOR CRM PAYMENTS
CREATE INDEX IF NOT EXISTS idx_crm_payments_user_id ON public.crm_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_crm_payments_client_id ON public.crm_payments(crm_client_id);
CREATE INDEX IF NOT EXISTS idx_income_crm_payment_id ON public.income(crm_payment_id);

-- RLS ENABLMENT & POLICIES FOR CRM PAYMENTS
ALTER TABLE public.crm_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can insert own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can update own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can delete own crm_payments" ON public.crm_payments;

CREATE POLICY "Users can select own crm_payments" ON public.crm_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own crm_payments" ON public.crm_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own crm_payments" ON public.crm_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own crm_payments" ON public.crm_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC POSTGRESQL RPC FOR CRM PAYMENT RECORDING (STRICT PAYMENT IDEMPOTENCY)
CREATE OR REPLACE FUNCTION public.record_crm_payment(
    p_payment_id UUID,
    p_crm_client_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'bKash',
    p_notes TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_client_name TEXT;
    v_business_name TEXT;
    v_quoted_price NUMERIC;
    v_current_advance NUMERIC;
    v_current_status TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_payment_id UUID;
    v_existing_payment RECORD;
    v_existing_income RECORD;
    v_new_advance NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    -- 1. Verify user authentication
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input values
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required for idempotency tracking';
    END IF;

    -- 3. Verify client ownership and fetch client details
    SELECT client_name, business_name, COALESCE(quoted_price, 0), COALESCE(advance, 0), status
    INTO v_client_name, v_business_name, v_quoted_price, v_current_advance, v_current_status
    FROM public.crm_clients
    WHERE id = p_crm_client_id AND user_id = v_user_id;

    IF v_client_name IS NULL THEN
        RAISE EXCEPTION 'CRM Client not found or access denied';
    END IF;

    -- 4. Check for existing payment ID (Strict Database Idempotency Check)
    SELECT * INTO v_existing_payment
    FROM public.crm_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        -- Return existing payment and linked income WITHOUT creating duplicates or incrementing advance
        SELECT * INTO v_existing_income
        FROM public.income
        WHERE crm_payment_id = p_payment_id AND user_id = v_user_id;

        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'income_id', COALESCE(v_existing_payment.income_id, v_existing_income.id),
            'client_id', p_crm_client_id,
            'amount', v_existing_payment.amount,
            'current_advance', v_current_advance,
            'status', v_current_status,
            'message', 'Payment already recorded previously. Duplicate request safely skipped.'
        );
    END IF;

    -- 5. Validate overpayment if quoted_price is set (> 0)
    IF v_quoted_price > 0 AND (v_current_advance + p_amount) > (v_quoted_price + 0.01) THEN
        RAISE EXCEPTION 'Payment of % would exceed quoted price of % (Current received: %)', 
            p_amount, v_quoted_price, v_current_advance;
    END IF;

    -- 6. Format client details for Income record
    IF v_business_name IS NOT NULL AND length(trim(v_business_name)) > 0 THEN
        v_client_details := v_client_name || ' (' || trim(v_business_name) || ')';
    ELSE
        v_client_details := v_client_name;
    END IF;

    v_payment_id := p_payment_id;

    -- 7. Create Payment record FIRST (Primary transaction record)
    INSERT INTO public.crm_payments (
        id,
        user_id,
        crm_client_id,
        payment_date,
        amount,
        payment_method,
        notes
    ) VALUES (
        v_payment_id,
        v_user_id,
        p_crm_client_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        COALESCE(p_notes, '')
    );

    -- 8. Create corresponding Income record linked via crm_payment_id
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes,
        crm_payment_id
    ) VALUES (
        v_user_id,
        p_payment_date,
        'CRM / Service',
        v_client_details,
        p_amount,
        p_payment_method,
        'Month 1',
        COALESCE(p_notes, ''),
        v_payment_id
    )
    RETURNING id INTO v_income_id;

    -- 9. Update crm_payments with linked income_id
    UPDATE public.crm_payments
    SET income_id = v_income_id
    WHERE id = v_payment_id;

    -- 10. Update crm_clients status if fully paid (DO NOT update advance to prevent double-counting in frontend)
    v_new_advance := v_current_advance + p_amount;
    v_new_status := v_current_status;

    IF v_quoted_price > 0 AND v_new_advance >= v_quoted_price THEN
        v_new_status := 'Paid';
    ELSIF v_new_advance > 0 AND (v_current_status = 'New' OR v_current_status = 'Negotiation' OR v_current_status = 'Proposal Sent') THEN
        v_new_status := 'Advance Paid';
    END IF;

    UPDATE public.crm_clients
    SET status = v_new_status,
        updated_at = NOW()
    WHERE id = p_crm_client_id AND user_id = v_user_id;

    -- 11. Build and return result JSON
    SELECT jsonb_build_object(
        'success', true,
        'idempotent_retry', false,
        'payment_id', v_payment_id,
        'income_id', v_income_id,
        'client_id', p_crm_client_id,
        'amount', p_amount,
        'payment_date', p_payment_date,
        'payment_method', p_payment_method,
        'new_advance', v_new_advance,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- CUSTOMER DUES / পাওনা MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 15. CUSTOMER DUES (TRANSACTIONS) TABLE
CREATE TABLE IF NOT EXISTS public.customer_dues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    customer_id BIGINT NULL REFERENCES public.crm_clients(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    description TEXT NOT NULL,
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    paid_amount NUMERIC NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    due_amount NUMERIC NOT NULL DEFAULT 0 CHECK (due_amount >= 0),
    due_date DATE NULL,
    status TEXT NOT NULL DEFAULT 'Unpaid' CHECK (status IN ('Unpaid', 'Partially Paid', 'Paid', 'Overdue')),
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. CUSTOMER DUE PAYMENTS HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.customer_due_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    due_id BIGINT NOT NULL REFERENCES public.customer_dues(id) ON DELETE CASCADE,
    customer_id BIGINT NULL REFERENCES public.crm_clients(id) ON DELETE SET NULL,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method TEXT NOT NULL DEFAULT 'bKash',
    note TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES FOR FAST DUES SEARCH
CREATE INDEX IF NOT EXISTS idx_customer_dues_user_id ON public.customer_dues(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_dues_customer_id ON public.customer_dues(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_dues_status ON public.customer_dues(status);
CREATE INDEX IF NOT EXISTS idx_customer_due_payments_user_id ON public.customer_due_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_due_payments_due_id ON public.customer_due_payments(due_id);

-- RLS ENABLMENT & POLICIES FOR DUES
ALTER TABLE public.customer_dues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_due_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can insert own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can update own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can delete own customer_dues" ON public.customer_dues;

CREATE POLICY "Users can select own customer_dues" ON public.customer_dues FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own customer_dues" ON public.customer_dues FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own customer_dues" ON public.customer_dues FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own customer_dues" ON public.customer_dues FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can insert own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can update own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can delete own customer_due_payments" ON public.customer_due_payments;

CREATE POLICY "Users can select own customer_due_payments" ON public.customer_due_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own customer_due_payments" ON public.customer_due_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own customer_due_payments" ON public.customer_due_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own customer_due_payments" ON public.customer_due_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC POSTGRESQL RPC FOR RECORDING CUSTOMER DUE PAYMENT & INCOME CREATION
CREATE OR REPLACE FUNCTION public.record_customer_due_payment(
    p_payment_id UUID,
    p_due_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'bKash',
    p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_customer_id BIGINT;
    v_customer_name TEXT;
    v_description TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_new_paid NUMERIC;
    v_new_due NUMERIC;
    v_new_status TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_existing_payment RECORD;
    v_result JSONB;
BEGIN
    -- 1. Authentication check
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input parameters
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required for idempotency tracking';
    END IF;

    -- 3. Retrieve due record
    SELECT customer_id, customer_name, description, total_amount, paid_amount
    INTO v_customer_id, v_customer_name, v_description, v_total_amount, v_current_paid
    FROM public.customer_dues
    WHERE id = p_due_id AND user_id = v_user_id;

    IF v_customer_name IS NULL THEN
        RAISE EXCEPTION 'Due record not found or access denied';
    END IF;

    -- 4. Check for duplicate payment (Idempotency)
    SELECT * INTO v_existing_payment
    FROM public.customer_due_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded previously. Duplicate request safely skipped.'
        );
    END IF;

    -- 5. Calculate new balances
    v_new_paid := v_current_paid + p_amount;
    v_new_due := GREATEST(0, v_total_amount - v_new_paid);

    IF v_new_due = 0 THEN
        v_new_status := 'Paid';
    ELSE
        v_new_status := 'Partially Paid';
    END IF;

    -- 6. Format client details for Income record
    v_client_details := v_customer_name || ' (' || v_description || ')';

    -- 7. Insert Income record linked to this payment
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes
    ) VALUES (
        v_user_id,
        p_payment_date,
        'Customer Payment',
        v_client_details,
        p_amount,
        p_payment_method,
        'Month 1',
        COALESCE(p_note, '')
    )
    RETURNING id INTO v_income_id;

    -- 8. Insert Due Payment record
    INSERT INTO public.customer_due_payments (
        id,
        user_id,
        due_id,
        customer_id,
        amount,
        payment_date,
        payment_method,
        note,
        income_id
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_due_id,
        v_customer_id,
        p_amount,
        p_payment_date,
        p_payment_method,
        COALESCE(p_note, ''),
        v_income_id
    );

    -- 9. Update Customer Dues summary
    UPDATE public.customer_dues
    SET paid_amount = v_new_paid,
        due_amount = v_new_due,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_due_id AND user_id = v_user_id;

    -- 10. Build result object
    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'income_id', v_income_id,
        'due_id', p_due_id,
        'amount', p_amount,
        'new_paid', v_new_paid,
        'new_due', v_new_due,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- LIABILITY / DEBT MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 17. LIABILITIES TABLE
CREATE TABLE IF NOT EXISTS public.liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    creditor_name TEXT NOT NULL,
    liability_type TEXT NOT NULL DEFAULT 'Hawlad', -- 'Hawlad', 'Bank Loan', 'EMI', 'Other'
    total_amount NUMERIC NOT NULL CHECK (total_amount > 0),
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    remaining_amount NUMERIC NOT NULL DEFAULT 0,
    due_date DATE NULL,
    emi_amount NUMERIC DEFAULT 0,
    duration_months INT DEFAULT 0,
    start_date DATE NULL,
    due_day INT NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Paid Off')),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 17.1 EMI INSTALLMENTS TABLE
CREATE TABLE IF NOT EXISTS public.emi_installments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    liability_id BIGINT NOT NULL REFERENCES public.liabilities(id) ON DELETE CASCADE,
    installment_number INT NOT NULL,
    due_date DATE NOT NULL,
    expected_amount NUMERIC NOT NULL,
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Upcoming' CHECK (status IN ('Upcoming', 'Due', 'Partial', 'Paid', 'Overdue')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (liability_id, installment_number)
);

-- 18. LIABILITY PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.liability_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    liability_id BIGINT NOT NULL REFERENCES public.liabilities(id) ON DELETE CASCADE,
    emi_installment_id UUID NULL REFERENCES public.emi_installments(id) ON DELETE SET NULL,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    expense_id BIGINT NULL REFERENCES public.expenses(id) ON DELETE SET NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_liabilities_user_id ON public.liabilities(user_id);
CREATE INDEX IF NOT EXISTS idx_emi_installments_user_id ON public.emi_installments(user_id);
CREATE INDEX IF NOT EXISTS idx_emi_installments_liability_id ON public.emi_installments(liability_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_user_id ON public.liability_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_liability_id ON public.liability_payments(liability_id);

-- RLS
ALTER TABLE public.liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emi_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liability_payments ENABLE ROW LEVEL SECURITY;

-- POLICIES
DROP POLICY IF EXISTS "Users can select own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can insert own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can update own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can delete own liabilities" ON public.liabilities;

CREATE POLICY "Users can select own liabilities" ON public.liabilities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liabilities" ON public.liabilities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liabilities" ON public.liabilities FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liabilities" ON public.liabilities FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can insert own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can update own emi_installments" ON public.emi_installments;
DROP POLICY IF EXISTS "Users can delete own emi_installments" ON public.emi_installments;

CREATE POLICY "Users can select own emi_installments" ON public.emi_installments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own emi_installments" ON public.emi_installments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own emi_installments" ON public.emi_installments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own emi_installments" ON public.emi_installments FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can insert own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can update own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can delete own liability_payments" ON public.liability_payments;

CREATE POLICY "Users can select own liability_payments" ON public.liability_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liability_payments" ON public.liability_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liability_payments" ON public.liability_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liability_payments" ON public.liability_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC RPC FOR RECORDING LIABILITY PAYMENT
CREATE OR REPLACE FUNCTION public.record_liability_payment(
    p_payment_id UUID,
    p_liability_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_notes TEXT DEFAULT '',
    p_add_to_expense BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_creditor_name TEXT;
    v_liability_type TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_existing_payment RECORD;
    v_expense_id BIGINT;
    v_new_paid NUMERIC;
    v_new_remaining NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required';
    END IF;

    SELECT creditor_name, liability_type, COALESCE(total_amount, 0), COALESCE(paid_amount, 0)
    INTO v_creditor_name, v_liability_type, v_total_amount, v_current_paid
    FROM public.liabilities
    WHERE id = p_liability_id AND user_id = v_user_id;

    IF v_creditor_name IS NULL THEN
        RAISE EXCEPTION 'Liability not found or access denied';
    END IF;

    -- Idempotency check
    SELECT * INTO v_existing_payment
    FROM public.liability_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded safely.'
        );
    END IF;
    
    -- Insert Expense if requested
    IF p_add_to_expense THEN
        -- Generate a unique BIGINT ID using timestamp to avoid sequence desync issues
        v_expense_id := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;
        
        INSERT INTO public.expenses (
            id,
            user_id,
            date,
            category,
            description,
            amount,
            month,
            notes
        ) VALUES (
            v_expense_id,
            v_user_id,
            p_payment_date,
            v_liability_type || ' Repayment',
            'Repaid to: ' || v_creditor_name,
            p_amount,
            'Month 1',
            COALESCE(p_notes, '')
        );
    END IF;

    -- Insert Payment Record
    INSERT INTO public.liability_payments (
        id,
        user_id,
        liability_id,
        payment_date,
        amount,
        payment_method,
        expense_id,
        notes
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_liability_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        v_expense_id,
        COALESCE(p_notes, '')
    );

    -- Update Liability summary
    v_new_paid := v_current_paid + p_amount;
    v_new_remaining := GREATEST(0, v_total_amount - v_new_paid);
    
    IF v_new_paid >= v_total_amount THEN
        v_new_status := 'Paid Off';
    ELSE
        v_new_status := 'Active';
    END IF;

    UPDATE public.liabilities
    SET paid_amount = v_new_paid,
        remaining_amount = v_new_remaining,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_liability_id AND user_id = v_user_id;

    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'expense_id', v_expense_id,
        'new_paid', v_new_paid,
        'new_remaining', v_new_remaining,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;






-- ATOMIC RPC FOR RECORDING EMI PAYMENT
CREATE OR REPLACE FUNCTION public.record_emi_payment(
    p_payment_id UUID,
    p_liability_id BIGINT,
    p_installment_id UUID,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_notes TEXT DEFAULT '',
    p_add_to_expense BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_creditor_name TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_existing_payment RECORD;
    v_expense_id BIGINT;
    v_installment_expected NUMERIC;
    v_installment_paid NUMERIC;
    v_new_installment_paid NUMERIC;
    v_new_installment_status TEXT;
    v_new_paid NUMERIC;
    v_new_remaining NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required';
    END IF;

    -- Fetch Liability Details
    SELECT creditor_name, COALESCE(total_amount, 0), COALESCE(paid_amount, 0)
    INTO v_creditor_name, v_total_amount, v_current_paid
    FROM public.liabilities
    WHERE id = p_liability_id AND user_id = v_user_id;

    IF v_creditor_name IS NULL THEN
        RAISE EXCEPTION 'Liability not found or access denied';
    END IF;

    -- Fetch Installment Details
    SELECT expected_amount, COALESCE(paid_amount, 0)
    INTO v_installment_expected, v_installment_paid
    FROM public.emi_installments
    WHERE id = p_installment_id AND liability_id = p_liability_id AND user_id = v_user_id;

    IF v_installment_expected IS NULL THEN
        RAISE EXCEPTION 'EMI Installment not found or access denied';
    END IF;

    -- Validate payment amount does not exceed installment remaining
    IF p_amount > (v_installment_expected - v_installment_paid) THEN
        RAISE EXCEPTION 'Payment amount exceeds remaining amount for this installment';
    END IF;

    -- Idempotency check
    SELECT * INTO v_existing_payment
    FROM public.liability_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded safely.'
        );
    END IF;
    
    -- Insert Expense if requested
    IF p_add_to_expense THEN
        -- Generate a unique BIGINT ID using timestamp to avoid sequence desync issues
        v_expense_id := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;
        
        INSERT INTO public.expenses (
            id,
            user_id,
            date,
            category,
            description,
            amount,
            month,
            notes
        ) VALUES (
            v_expense_id,
            v_user_id,
            p_payment_date,
            'EMI Repayment',
            'Repaid to: ' || v_creditor_name,
            p_amount,
            'Month 1',
            COALESCE(p_notes, '')
        );
    END IF;

    -- Insert Payment Record linked to EMI installment
    INSERT INTO public.liability_payments (
        id,
        user_id,
        liability_id,
        emi_installment_id,
        payment_date,
        amount,
        payment_method,
        expense_id,
        notes
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_liability_id,
        p_installment_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        v_expense_id,
        COALESCE(p_notes, '')
    );

    -- Update Installment summary
    v_new_installment_paid := v_installment_paid + p_amount;
    
    IF v_new_installment_paid >= v_installment_expected THEN
        v_new_installment_status := 'Paid';
    ELSE
        v_new_installment_status := 'Partial';
    END IF;

    UPDATE public.emi_installments
    SET paid_amount = v_new_installment_paid,
        status = v_new_installment_status,
        payment_date = COALESCE(payment_date, p_payment_date),
        updated_at = NOW()
    WHERE id = p_installment_id AND user_id = v_user_id;

    -- Update Liability summary
    v_new_paid := v_current_paid + p_amount;
    v_new_remaining := GREATEST(0, v_total_amount - v_new_paid);
    
    IF v_new_paid >= v_total_amount THEN
        v_new_status := 'Paid Off';
    ELSE
        v_new_status := 'Active';
    END IF;

    UPDATE public.liabilities
    SET paid_amount = v_new_paid,
        remaining_amount = v_new_remaining,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_liability_id AND user_id = v_user_id;

    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'expense_id', v_expense_id,
        'installment_status', v_new_installment_status,
        'new_paid', v_new_paid,
        'new_remaining', v_new_remaining,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

 - -   N e w   D a s h b o a r d   T o t a l s   R P C 
 C R E A T E   O R   R E P L A C E   F U N C T I O N   g e t _ d a s h b o a r d _ t o t a l s ( p _ u s e r _ i d   U U I D ) 
 R E T U R N S   T A B L E   ( 
     t o t a l _ i n c o m e   N U M E R I C , 
     t o t a l _ e x p e n s e s   N U M E R I C , 
     t a r g e t _ i n c o m e   N U M E R I C , 
     r e m a i n i n g _ t a r g e t   N U M E R I C 
 ) 
 L A N G U A G E   s q l 
 S E C U R I T Y   D E F I N E R 
 A S   \ $ \ $ 
     S E L E C T 
         C O A L E S C E ( ( S E L E C T   S U M ( a m o u n t )   F R O M   i n c o m e   W H E R E   u s e r _ i d   =   p _ u s e r _ i d ) ,   0 )   A S   t o t a l _ i n c o m e , 
         C O A L E S C E ( ( S E L E C T   S U M ( a m o u n t )   F R O M   e x p e n s e s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d ) ,   0 )   A S   t o t a l _ e x p e n s e s , 
         C O A L E S C E ( ( S E L E C T   t a r g e t _ i n c o m e   F R O M   s e t t i n g s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   L I M I T   1 ) ,   0 )   A S   t a r g e t _ i n c o m e , 
         G R E A T E S T ( 0 ,   C O A L E S C E ( ( S E L E C T   t a r g e t _ i n c o m e   F R O M   s e t t i n g s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   L I M I T   1 ) ,   0 )   -   C O A L E S C E ( ( S E L E C T   S U M ( a m o u n t )   F R O M   i n c o m e   W H E R E   u s e r _ i d   =   p _ u s e r _ i d ) ,   0 ) )   A S   r e m a i n i n g _ t a r g e t ; 
 \ $ \ $ ; 
  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
 - -   D A S H B O A R D   T O T A L S   R P C   ( F I X   3 )  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
  
 C R E A T E   O R   R E P L A C E   F U N C T I O N   p u b l i c . g e t _ d a s h b o a r d _ f i n a n c i a l _ t o t a l s ( p _ u s e r _ i d   U U I D )  
 R E T U R N S   J S O N B  
 L A N G U A G E   p l p g s q l  
 S E C U R I T Y   D E F I N E R  
 S E T   s e a r c h _ p a t h   =   p u b l i c ,   p g _ t e m p  
 A S   $ $  
 D E C L A R E  
         v _ t a r g e t _ i n c o m e   N U M E R I C   : =   1 0 0 0 0 0 ;  
         v _ t o t a l _ s a l a r y   N U M E R I C   : =   0 ;  
         v _ t o t a l _ n e w _ i n c o m e   N U M E R I C   : =   0 ;  
         v _ t o t a l _ e x p e n s e s   N U M E R I C   : =   0 ;  
 B E G I N  
         S E L E C T   C O A L E S C E ( t a r g e t _ i n c o m e ,   1 0 0 0 0 0 )   I N T O   v _ t a r g e t _ i n c o m e  
         F R O M   p u b l i c . s e t t i n g s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   L I M I T   1 ;  
  
         S E L E C T   C O A L E S C E ( S U M ( a m o u n t ) ,   0 )   I N T O   v _ t o t a l _ s a l a r y  
         F R O M   p u b l i c . i n c o m e   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   s o u r c e   I L I K E   ' % S a l a r y % ' ;  
  
         S E L E C T   C O A L E S C E ( S U M ( a m o u n t ) ,   0 )   I N T O   v _ t o t a l _ n e w _ i n c o m e  
         F R O M   p u b l i c . i n c o m e   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   s o u r c e   N O T   I L I K E   ' % S a l a r y % ' ;  
  
         S E L E C T   C O A L E S C E ( S U M ( a m o u n t ) ,   0 )   I N T O   v _ t o t a l _ e x p e n s e s  
         F R O M   p u b l i c . e x p e n s e s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d ;  
  
         R E T U R N   j s o n b _ b u i l d _ o b j e c t (  
                 ' t a r g e t I n c o m e ' ,   v _ t a r g e t _ i n c o m e ,  
                 ' s a l a r y S u m ' ,   v _ t o t a l _ s a l a r y ,  
                 ' n e w I n c o m e S u m ' ,   v _ t o t a l _ n e w _ i n c o m e ,  
                 ' t o t a l E x p e n s e s ' ,   v _ t o t a l _ e x p e n s e s  
         ) ;  
 E N D ;  
 $ $ ;  
  
 C R E A T E   O R   R E P L A C E   F U N C T I O N   p u b l i c . g e t _ d a s h b o a r d _ t u i t i o n _ a n d _ d u e s _ t o t a l s (  
         p _ u s e r _ i d   U U I D ,    
         p _ c u r r e n t _ m o n t h _ s t r   T E X T ,    
         p _ t o d a y _ s t r   D A T E ,    
         p _ n e x t _ 7 _ d a y s _ s t r   D A T E  
 )  
 R E T U R N S   J S O N B  
 L A N G U A G E   p l p g s q l  
 S E C U R I T Y   D E F I N E R  
 S E T   s e a r c h _ p a t h   =   p u b l i c ,   p g _ t e m p  
 A S   $ $  
 D E C L A R E  
         v _ e x p e c t e d _ t u i t i o n   N U M E R I C   : =   0 ;  
         v _ c o l l e c t e d _ t u i t i o n   N U M E R I C   : =   0 ;  
         v _ t o t a l _ d u e s   N U M E R I C   : =   0 ;  
         v _ o v e r d u e _ d u e s   N U M E R I C   : =   0 ;  
         v _ d u e _ s o o n _ d u e s   N U M E R I C   : =   0 ;  
 B E G I N  
         S E L E C T   C O A L E S C E ( S U M ( m o n t h l y _ f e e ) ,   0 )   I N T O   v _ e x p e c t e d _ t u i t i o n  
         F R O M   p u b l i c . t u i t i o n _ s t u d e n t s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   s t a t u s   =   ' A c t i v e ' ;  
  
         S E L E C T   C O A L E S C E ( S U M ( a m o u n t ) ,   0 )   I N T O   v _ c o l l e c t e d _ t u i t i o n  
         F R O M   p u b l i c . t u i t i o n _ p a y m e n t s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   p a y m e n t _ m o n t h   =   p _ c u r r e n t _ m o n t h _ s t r ;  
  
         S E L E C T   C O A L E S C E ( S U M ( G R E A T E S T ( 0 ,   t o t a l _ a m o u n t   -   p a i d _ a m o u n t ) ) ,   0 )   I N T O   v _ t o t a l _ d u e s  
         F R O M   p u b l i c . c u s t o m e r _ d u e s   W H E R E   u s e r _ i d   =   p _ u s e r _ i d ;  
  
         S E L E C T   C O A L E S C E ( S U M ( G R E A T E S T ( 0 ,   t o t a l _ a m o u n t   -   p a i d _ a m o u n t ) ) ,   0 )   I N T O   v _ o v e r d u e _ d u e s  
         F R O M   p u b l i c . c u s t o m e r _ d u e s    
         W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   d u e _ d a t e   <   p _ t o d a y _ s t r   A N D   ( t o t a l _ a m o u n t   -   p a i d _ a m o u n t )   >   0 ;  
  
         S E L E C T   C O A L E S C E ( S U M ( G R E A T E S T ( 0 ,   t o t a l _ a m o u n t   -   p a i d _ a m o u n t ) ) ,   0 )   I N T O   v _ d u e _ s o o n _ d u e s  
         F R O M   p u b l i c . c u s t o m e r _ d u e s    
         W H E R E   u s e r _ i d   =   p _ u s e r _ i d   A N D   d u e _ d a t e   > =   p _ t o d a y _ s t r   A N D   d u e _ d a t e   < =   p _ n e x t _ 7 _ d a y s _ s t r   A N D   ( t o t a l _ a m o u n t   -   p a i d _ a m o u n t )   >   0 ;  
  
         R E T U R N   j s o n b _ b u i l d _ o b j e c t (  
                 ' e x p e c t e d T u i t i o n ' ,   v _ e x p e c t e d _ t u i t i o n ,  
                 ' c o l l e c t e d T u i t i o n ' ,   v _ c o l l e c t e d _ t u i t i o n ,  
                 ' t o t a l D u e s ' ,   v _ t o t a l _ d u e s ,  
                 ' o v e r d u e D u e s ' ,   v _ o v e r d u e _ d u e s ,  
                 ' d u e S o o n D u e s ' ,   v _ d u e _ s o o n _ d u e s  
         ) ;  
 E N D ;  
 $ $ ;  
 