-- ====================================================================
-- SUPABASE POSTGRESQL SCHEMA FOR PERSONAL BUSINESS MANAGEMENT APP
-- ====================================================================

-- 1. ENABLE EXTENSION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    target_income NUMERIC NOT NULL DEFAULT 100000,
    installment NUMERIC NOT NULL DEFAULT 80000,
    daily_outreach_target INT NOT NULL DEFAULT 10,
    currency TEXT NOT NULL DEFAULT '৳',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_settings UNIQUE(user_id)
);

-- 3. TASKS TABLE
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Sales',
    priority TEXT NOT NULL DEFAULT 'High',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    target_metric TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'NotStarted',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. CRM CLIENTS (LEADS) TABLE
CREATE TABLE IF NOT EXISTS public.crm_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    client_name TEXT NOT NULL,
    business_name TEXT NOT NULL,
    contact TEXT DEFAULT '',
    service TEXT DEFAULT '',
    quoted_price NUMERIC DEFAULT 0,
    advance NUMERIC DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'New',
    next_follow_up DATE NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. INCOME TABLE
CREATE TABLE IF NOT EXISTS public.income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    source TEXT NOT NULL,
    client_details TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    payment_type TEXT DEFAULT 'bKash',
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. EXPENSES TABLE
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    month TEXT DEFAULT 'Month 1',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. WEEKLY REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.weekly_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    week_title TEXT NOT NULL,
    outreach_count INT DEFAULT 0,
    replies_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    clients_won_count INT DEFAULT 0,
    new_income NUMERIC DEFAULT 0,
    main_achievement TEXT DEFAULT '',
    main_problem TEXT DEFAULT '',
    next_week_priority TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    delivery_time TEXT DEFAULT '',
    includes TEXT[] DEFAULT '{}',
    notes TEXT DEFAULT '',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. NINETY DAY PLAN TABLE
CREATE TABLE IF NOT EXISTS public.ninety_day_plan (
    id TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    month_title TEXT NOT NULL,
    target_income TEXT DEFAULT '',
    new_income_target TEXT DEFAULT '',
    focus TEXT DEFAULT '',
    weeks JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, user_id)
);

-- 10. SUBSCRIPTIONS TABLE (Current User Access State)
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'unpaid', -- 'unpaid', 'pending', 'active', 'expired', 'rejected'
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    billing_cycle TEXT NOT NULL DEFAULT 'monthly',
    starts_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_subscription UNIQUE(user_id)
);

-- Ensure billing_cycle and plan_id exists for additive migration
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS billing_cycle TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS plan_id TEXT;

-- 11. PAYMENT REQUESTS TABLE (Payment Submission & Renewal History)
CREATE TABLE IF NOT EXISTS public.payment_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    user_email TEXT NOT NULL,
    plan_name TEXT NOT NULL DEFAULT 'Monthly Pro',
    amount NUMERIC NOT NULL DEFAULT 500,
    payment_method TEXT NOT NULL, -- 'bKash', 'Nagad', 'Rocket'
    sender_number TEXT NOT NULL,
    trx_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    admin_notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure plan_id exists for additive migration
ALTER TABLE public.payment_requests ADD COLUMN IF NOT EXISTS plan_id TEXT;

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ninety_day_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_requests ENABLE ROW LEVEL SECURITY;

-- SETTINGS POLICIES
DROP POLICY IF EXISTS "Users can select own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can insert own settings" ON public.settings;
DROP POLICY IF EXISTS "Users can update own settings" ON public.settings;
CREATE POLICY "Users can select own settings" ON public.settings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own settings" ON public.settings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own settings" ON public.settings FOR UPDATE USING (auth.uid() = user_id);

-- TASKS POLICIES
DROP POLICY IF EXISTS "Users can select own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can insert own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can update own tasks" ON public.tasks;
DROP POLICY IF EXISTS "Users can delete own tasks" ON public.tasks;
CREATE POLICY "Users can select own tasks" ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tasks" ON public.tasks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tasks" ON public.tasks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tasks" ON public.tasks FOR DELETE USING (auth.uid() = user_id);

-- CRM CLIENTS POLICIES
DROP POLICY IF EXISTS "Users can select own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can insert own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can update own crm_clients" ON public.crm_clients;
DROP POLICY IF EXISTS "Users can delete own crm_clients" ON public.crm_clients;
CREATE POLICY "Users can select own crm_clients" ON public.crm_clients FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own crm_clients" ON public.crm_clients FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own crm_clients" ON public.crm_clients FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own crm_clients" ON public.crm_clients FOR DELETE USING (auth.uid() = user_id);

-- INCOME POLICIES
DROP POLICY IF EXISTS "Users can select own income" ON public.income;
DROP POLICY IF EXISTS "Users can insert own income" ON public.income;
DROP POLICY IF EXISTS "Users can update own income" ON public.income;
DROP POLICY IF EXISTS "Users can delete own income" ON public.income;
CREATE POLICY "Users can select own income" ON public.income FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own income" ON public.income FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own income" ON public.income FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own income" ON public.income FOR DELETE USING (auth.uid() = user_id);

-- EXPENSES POLICIES
DROP POLICY IF EXISTS "Users can select own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
CREATE POLICY "Users can select own expenses" ON public.expenses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own expenses" ON public.expenses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own expenses" ON public.expenses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own expenses" ON public.expenses FOR DELETE USING (auth.uid() = user_id);

-- WEEKLY REVIEWS POLICIES
DROP POLICY IF EXISTS "Users can select own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can insert own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can update own weekly_reviews" ON public.weekly_reviews;
DROP POLICY IF EXISTS "Users can delete own weekly_reviews" ON public.weekly_reviews;
CREATE POLICY "Users can select own weekly_reviews" ON public.weekly_reviews FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own weekly_reviews" ON public.weekly_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own weekly_reviews" ON public.weekly_reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own weekly_reviews" ON public.weekly_reviews FOR DELETE USING (auth.uid() = user_id);

-- SERVICES POLICIES
DROP POLICY IF EXISTS "Users can select own services" ON public.services;
DROP POLICY IF EXISTS "Users can insert own services" ON public.services;
DROP POLICY IF EXISTS "Users can update own services" ON public.services;
DROP POLICY IF EXISTS "Users can delete own services" ON public.services;
CREATE POLICY "Users can select own services" ON public.services FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own services" ON public.services FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own services" ON public.services FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own services" ON public.services FOR DELETE USING (auth.uid() = user_id);

-- NINETY DAY PLAN POLICIES
DROP POLICY IF EXISTS "Users can select own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can insert own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can update own ninety_day_plan" ON public.ninety_day_plan;
DROP POLICY IF EXISTS "Users can delete own ninety_day_plan" ON public.ninety_day_plan;
CREATE POLICY "Users can select own ninety_day_plan" ON public.ninety_day_plan FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own ninety_day_plan" ON public.ninety_day_plan FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ninety_day_plan" ON public.ninety_day_plan FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ninety_day_plan" ON public.ninety_day_plan FOR DELETE USING (auth.uid() = user_id);

-- ====================================================================
-- USER ROLES & ADMINISTRATIVE AUTHORIZATION
-- ====================================================================

CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_role UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- SECURITY DEFINER function to verify if a user has an admin role
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF p_user_id IS NULL THEN
        RETURN FALSE;
    END IF;
    RETURN EXISTS (
        SELECT 1 
        FROM public.user_roles 
        WHERE user_id = p_user_id 
          AND role = 'admin'
    );
END;
$$;

-- RLS Policy for user_roles table
DROP POLICY IF EXISTS "Users can view own role or admin can view all" ON public.user_roles;
CREATE POLICY "Users can view own role or admin can view all" 
    ON public.user_roles FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

-- Insert initial admin role for existing admin user if present in auth.users
INSERT INTO public.user_roles (user_id, role)
SELECT id, 'admin'
FROM auth.users
WHERE email = 'fuwaraahmed@gmail.com'
ON CONFLICT (user_id, role) DO NOTHING;

-- SUBSCRIPTIONS POLICIES
DROP POLICY IF EXISTS "Users can view own subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can insert own initial subscription" ON public.subscriptions;
DROP POLICY IF EXISTS "Users can update own subscription to pending" ON public.subscriptions;
CREATE POLICY "Users can view own subscription" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

CREATE POLICY "Users can insert own initial subscription" 
    ON public.subscriptions FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own subscription to pending" 
    ON public.subscriptions FOR UPDATE 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- PAYMENT REQUESTS POLICIES
DROP POLICY IF EXISTS "Users can view own payment requests" ON public.payment_requests;
DROP POLICY IF EXISTS "Users can submit own payment requests" ON public.payment_requests;
CREATE POLICY "Users can view own payment requests" 
    ON public.payment_requests FOR SELECT 
    USING (auth.uid() = user_id OR public.is_admin(auth.uid()));

CREATE POLICY "Users can submit own payment requests" 
    ON public.payment_requests FOR INSERT 
    WITH CHECK (auth.uid() = user_id AND status = 'pending');

-- ====================================================================
-- SERVER-SIDE ADMIN RPC APPROVAL FUNCTIONS (SECURITY DEFINER)
-- ====================================================================

-- 1. FUNCTION TO APPROVE PAYMENT REQUEST
CREATE OR REPLACE FUNCTION public.approve_payment_request(request_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    req RECORD;
    v_existing_sub RECORD;
    v_starts_at TIMESTAMPTZ;
    v_expires_at TIMESTAMPTZ;
BEGIN
    IF NOT public.is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Unauthorized: Only system administrators can approve payment requests.';
    END IF;

    SELECT * INTO req FROM public.payment_requests WHERE id = request_id AND status = 'pending';
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'approved', updated_at = NOW() 
    WHERE id = request_id;

    -- Fetch existing subscription to handle smart renewal logic
    SELECT * INTO v_existing_sub FROM public.subscriptions WHERE user_id = req.user_id;

    IF v_existing_sub IS NOT NULL AND v_existing_sub.status = 'active' AND v_existing_sub.expires_at > NOW() THEN
        -- Active subscription: extend from current expiry
        v_starts_at := v_existing_sub.starts_at;
        v_expires_at := v_existing_sub.expires_at + INTERVAL '1 month';
    ELSE
        -- Expired or new subscription: start from now
        v_starts_at := NOW();
        v_expires_at := NOW() + INTERVAL '1 month';
    END IF;

    INSERT INTO public.subscriptions (user_id, user_email, status, plan_id, plan_name, billing_cycle, starts_at, expires_at, updated_at)
    VALUES (req.user_id, req.user_email, 'active', req.plan_id, req.plan_name, 'monthly', v_starts_at, v_expires_at, NOW())
    ON CONFLICT (user_id) 
    DO UPDATE SET 
        status = 'active',
        plan_id = EXCLUDED.plan_id,
        plan_name = EXCLUDED.plan_name,
        billing_cycle = 'monthly',
        starts_at = v_starts_at,
        expires_at = v_expires_at,
        updated_at = NOW();

    RETURN jsonb_build_object('success', true, 'message', 'Payment request approved successfully.');
END;
$$;

-- 2. FUNCTION TO REJECT PAYMENT REQUEST
CREATE OR REPLACE FUNCTION public.reject_payment_request(request_id UUID, rejection_reason TEXT DEFAULT '')
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    req RECORD;
BEGIN
    IF NOT public.is_admin(auth.uid()) THEN
        RAISE EXCEPTION 'Unauthorized: Only system administrators can reject payment requests.';
    END IF;

    SELECT * INTO req FROM public.payment_requests WHERE id = request_id AND status = 'pending';
    
    IF req IS NULL THEN
        RAISE EXCEPTION 'Payment request not found or already processed.';
    END IF;

    UPDATE public.payment_requests 
    SET status = 'rejected', admin_notes = rejection_reason, updated_at = NOW() 
    WHERE id = request_id;

    UPDATE public.subscriptions 
    SET status = 'rejected', updated_at = NOW() 
    WHERE user_id = req.user_id AND status != 'active';

    RETURN jsonb_build_object('success', true, 'message', 'Payment request rejected.');
END;
$$;

-- ====================================================================
-- TUITION MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 12. TUITION STUDENTS TABLE
CREATE TABLE IF NOT EXISTS public.tuition_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    student_name TEXT NOT NULL,
    guardian_name TEXT DEFAULT '',
    mobile TEXT DEFAULT '',
    class_name TEXT DEFAULT '',
    batch TEXT DEFAULT '',
    monthly_fee NUMERIC NOT NULL CHECK (monthly_fee > 0),
    joining_date DATE NOT NULL DEFAULT CURRENT_DATE,
    billing_start_month TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Left', 'Inactive')),
    leaving_date DATE NULL,
    leaving_reason TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. TUITION PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.tuition_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    student_id BIGINT NOT NULL REFERENCES public.tuition_students(id) ON DELETE RESTRICT,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_month TEXT NOT NULL CHECK (payment_month ~ '^\d{4}-(0[1-9]|1[0-2])$'), -- Stored as 'YYYY-MM' (e.g. '2026-09')
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    note TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_student_monthly_payment UNIQUE (user_id, student_id, payment_month)
);

-- INDEXES FOR FAST SEARCH AND LOOKUP
CREATE INDEX IF NOT EXISTS idx_tuition_students_user_id ON public.tuition_students(user_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_user_id ON public.tuition_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_student_id ON public.tuition_payments(student_id);
CREATE INDEX IF NOT EXISTS idx_tuition_payments_month ON public.tuition_payments(payment_month);

-- RLS ENABLMENT
ALTER TABLE public.tuition_students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tuition_payments ENABLE ROW LEVEL SECURITY;

-- TUITION STUDENTS POLICIES
DROP POLICY IF EXISTS "Users can select own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can insert own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can update own tuition_students" ON public.tuition_students;
DROP POLICY IF EXISTS "Users can delete own tuition_students" ON public.tuition_students;

CREATE POLICY "Users can select own tuition_students" ON public.tuition_students FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tuition_students" ON public.tuition_students FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tuition_students" ON public.tuition_students FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tuition_students" ON public.tuition_students FOR DELETE USING (auth.uid() = user_id);

-- TUITION PAYMENTS POLICIES
DROP POLICY IF EXISTS "Users can select own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can insert own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can update own tuition_payments" ON public.tuition_payments;
DROP POLICY IF EXISTS "Users can delete own tuition_payments" ON public.tuition_payments;

CREATE POLICY "Users can select own tuition_payments" ON public.tuition_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tuition_payments" ON public.tuition_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tuition_payments" ON public.tuition_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tuition_payments" ON public.tuition_payments FOR DELETE USING (auth.uid() = user_id);

-- ====================================================================
-- ATOMIC POSTGRESQL RPC FOR TUITION PAYMENT & INCOME CREATION
-- ====================================================================
CREATE OR REPLACE FUNCTION public.record_tuition_payment(
    p_student_id BIGINT,
    p_payment_date DATE,
    p_payment_month TEXT,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_student_name TEXT;
    v_class_name TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_payment_id BIGINT;
    v_result JSONB;
BEGIN
    -- 1. Verify user authentication
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input values
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_month IS NULL OR p_payment_month !~ '^\d{4}-(0[1-9]|1[0-2])$' THEN
        RAISE EXCEPTION 'Invalid payment month format. Must be YYYY-MM (e.g. 2026-09)';
    END IF;

    -- 3. Verify student ownership and fetch student details
    SELECT student_name, class_name
    INTO v_student_name, v_class_name
    FROM public.tuition_students
    WHERE id = p_student_id AND user_id = v_user_id;

    IF v_student_name IS NULL THEN
        RAISE EXCEPTION 'Student not found or access denied';
    END IF;

    -- Format client_details cleanly without trailing hyphen when class_name is empty
    IF v_class_name IS NOT NULL AND length(trim(v_class_name)) > 0 THEN
        v_client_details := v_student_name || ' - ' || trim(v_class_name);
    ELSE
        v_client_details := v_student_name;
    END IF;

    -- 4. Check duplicate monthly payment
    IF EXISTS (
        SELECT 1 FROM public.tuition_payments
        WHERE user_id = v_user_id
          AND student_id = p_student_id
          AND payment_month = p_payment_month
    ) THEN
        RAISE EXCEPTION 'A payment for month % already exists for this student', p_payment_month;
    END IF;

    -- 5. Create Income record
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes
    ) VALUES (
        v_user_id,
        p_payment_date,
        'Tuition',
        v_client_details,
        p_amount,
        p_payment_method,
        p_payment_month,
        COALESCE(p_note, '')
    )
    RETURNING id INTO v_income_id;

    -- 6. Create Tuition Payment record linked to Income
    INSERT INTO public.tuition_payments (
        user_id,
        student_id,
        payment_date,
        payment_month,
        amount,
        payment_method,
        note,
        income_id
    ) VALUES (
        v_user_id,
        p_student_id,
        p_payment_date,
        p_payment_month,
        p_amount,
        p_payment_method,
        COALESCE(p_note, ''),
        v_income_id
    )
    RETURNING id INTO v_payment_id;

    -- 7. Build and return combined result JSON
    SELECT jsonb_build_object(
        'success', true,
        'payment_id', v_payment_id,
        'income_id', v_income_id,
        'student_id', p_student_id,
        'amount', p_amount,
        'payment_month', p_payment_month,
        'payment_date', p_payment_date,
        'payment_method', p_payment_method,
        'note', p_note
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- CRM PAYMENT MODULE SCHEMA, UNIQUE CONSTRAINT & ATOMIC RPC
-- ====================================================================

-- 14. CRM PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.crm_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    crm_client_id BIGINT NOT NULL REFERENCES public.crm_clients(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'bKash',
    notes TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ADD UNIQUE crm_payment_id TO INCOME TABLE FOR DATABASE-LEVEL IDEMPOTENCY
ALTER TABLE public.income ADD COLUMN IF NOT EXISTS crm_payment_id UUID UNIQUE NULL REFERENCES public.crm_payments(id) ON DELETE SET NULL;

-- INDEXES FOR CRM PAYMENTS
CREATE INDEX IF NOT EXISTS idx_crm_payments_user_id ON public.crm_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_crm_payments_client_id ON public.crm_payments(crm_client_id);
CREATE INDEX IF NOT EXISTS idx_income_crm_payment_id ON public.income(crm_payment_id);

-- RLS ENABLMENT & POLICIES FOR CRM PAYMENTS
ALTER TABLE public.crm_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can insert own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can update own crm_payments" ON public.crm_payments;
DROP POLICY IF EXISTS "Users can delete own crm_payments" ON public.crm_payments;

CREATE POLICY "Users can select own crm_payments" ON public.crm_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own crm_payments" ON public.crm_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own crm_payments" ON public.crm_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own crm_payments" ON public.crm_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC POSTGRESQL RPC FOR CRM PAYMENT RECORDING (STRICT PAYMENT IDEMPOTENCY)
CREATE OR REPLACE FUNCTION public.record_crm_payment(
    p_payment_id UUID,
    p_crm_client_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'bKash',
    p_notes TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_client_name TEXT;
    v_business_name TEXT;
    v_quoted_price NUMERIC;
    v_current_advance NUMERIC;
    v_current_status TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_payment_id UUID;
    v_existing_payment RECORD;
    v_existing_income RECORD;
    v_new_advance NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    -- 1. Verify user authentication
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input values
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required for idempotency tracking';
    END IF;

    -- 3. Verify client ownership and fetch client details
    SELECT client_name, business_name, COALESCE(quoted_price, 0), COALESCE(advance, 0), status
    INTO v_client_name, v_business_name, v_quoted_price, v_current_advance, v_current_status
    FROM public.crm_clients
    WHERE id = p_crm_client_id AND user_id = v_user_id;

    IF v_client_name IS NULL THEN
        RAISE EXCEPTION 'CRM Client not found or access denied';
    END IF;

    -- 4. Check for existing payment ID (Strict Database Idempotency Check)
    SELECT * INTO v_existing_payment
    FROM public.crm_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        -- Return existing payment and linked income WITHOUT creating duplicates or incrementing advance
        SELECT * INTO v_existing_income
        FROM public.income
        WHERE crm_payment_id = p_payment_id AND user_id = v_user_id;

        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'income_id', COALESCE(v_existing_payment.income_id, v_existing_income.id),
            'client_id', p_crm_client_id,
            'amount', v_existing_payment.amount,
            'current_advance', v_current_advance,
            'status', v_current_status,
            'message', 'Payment already recorded previously. Duplicate request safely skipped.'
        );
    END IF;

    -- 5. Validate overpayment if quoted_price is set (> 0)
    IF v_quoted_price > 0 AND (v_current_advance + p_amount) > (v_quoted_price + 0.01) THEN
        RAISE EXCEPTION 'Payment of % would exceed quoted price of % (Current received: %)', 
            p_amount, v_quoted_price, v_current_advance;
    END IF;

    -- 6. Format client details for Income record
    IF v_business_name IS NOT NULL AND length(trim(v_business_name)) > 0 THEN
        v_client_details := v_client_name || ' (' || trim(v_business_name) || ')';
    ELSE
        v_client_details := v_client_name;
    END IF;

    v_payment_id := p_payment_id;

    -- 7. Create Payment record FIRST (Primary transaction record)
    INSERT INTO public.crm_payments (
        id,
        user_id,
        crm_client_id,
        payment_date,
        amount,
        payment_method,
        notes
    ) VALUES (
        v_payment_id,
        v_user_id,
        p_crm_client_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        COALESCE(p_notes, '')
    );

    -- 8. Create corresponding Income record linked via crm_payment_id
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes,
        crm_payment_id
    ) VALUES (
        v_user_id,
        p_payment_date,
        'CRM / Service',
        v_client_details,
        p_amount,
        p_payment_method,
        'Month 1',
        COALESCE(p_notes, ''),
        v_payment_id
    )
    RETURNING id INTO v_income_id;

    -- 9. Update crm_payments with linked income_id
    UPDATE public.crm_payments
    SET income_id = v_income_id
    WHERE id = v_payment_id;

    -- 10. Update crm_clients status if fully paid (DO NOT update advance to prevent double-counting in frontend)
    v_new_advance := v_current_advance + p_amount;
    v_new_status := v_current_status;

    IF v_quoted_price > 0 AND v_new_advance >= v_quoted_price THEN
        v_new_status := 'Paid';
    ELSIF v_new_advance > 0 AND (v_current_status = 'New' OR v_current_status = 'Negotiation' OR v_current_status = 'Proposal Sent') THEN
        v_new_status := 'Advance Paid';
    END IF;

    UPDATE public.crm_clients
    SET status = v_new_status,
        updated_at = NOW()
    WHERE id = p_crm_client_id AND user_id = v_user_id;

    -- 11. Build and return result JSON
    SELECT jsonb_build_object(
        'success', true,
        'idempotent_retry', false,
        'payment_id', v_payment_id,
        'income_id', v_income_id,
        'client_id', p_crm_client_id,
        'amount', p_amount,
        'payment_date', p_payment_date,
        'payment_method', p_payment_method,
        'new_advance', v_new_advance,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- CUSTOMER DUES / পাওনা MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 15. CUSTOMER DUES (TRANSACTIONS) TABLE
CREATE TABLE IF NOT EXISTS public.customer_dues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    customer_id BIGINT NULL REFERENCES public.crm_clients(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    description TEXT NOT NULL,
    total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
    paid_amount NUMERIC NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    due_amount NUMERIC NOT NULL DEFAULT 0 CHECK (due_amount >= 0),
    due_date DATE NULL,
    status TEXT NOT NULL DEFAULT 'Unpaid' CHECK (status IN ('Unpaid', 'Partially Paid', 'Paid', 'Overdue')),
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. CUSTOMER DUE PAYMENTS HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.customer_due_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    due_id BIGINT NOT NULL REFERENCES public.customer_dues(id) ON DELETE CASCADE,
    customer_id BIGINT NULL REFERENCES public.crm_clients(id) ON DELETE SET NULL,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method TEXT NOT NULL DEFAULT 'bKash',
    note TEXT DEFAULT '',
    income_id BIGINT NULL REFERENCES public.income(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES FOR FAST DUES SEARCH
CREATE INDEX IF NOT EXISTS idx_customer_dues_user_id ON public.customer_dues(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_dues_customer_id ON public.customer_dues(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_dues_status ON public.customer_dues(status);
CREATE INDEX IF NOT EXISTS idx_customer_due_payments_user_id ON public.customer_due_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_customer_due_payments_due_id ON public.customer_due_payments(due_id);

-- RLS ENABLMENT & POLICIES FOR DUES
ALTER TABLE public.customer_dues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_due_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can insert own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can update own customer_dues" ON public.customer_dues;
DROP POLICY IF EXISTS "Users can delete own customer_dues" ON public.customer_dues;

CREATE POLICY "Users can select own customer_dues" ON public.customer_dues FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own customer_dues" ON public.customer_dues FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own customer_dues" ON public.customer_dues FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own customer_dues" ON public.customer_dues FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can insert own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can update own customer_due_payments" ON public.customer_due_payments;
DROP POLICY IF EXISTS "Users can delete own customer_due_payments" ON public.customer_due_payments;

CREATE POLICY "Users can select own customer_due_payments" ON public.customer_due_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own customer_due_payments" ON public.customer_due_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own customer_due_payments" ON public.customer_due_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own customer_due_payments" ON public.customer_due_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC POSTGRESQL RPC FOR RECORDING CUSTOMER DUE PAYMENT & INCOME CREATION
CREATE OR REPLACE FUNCTION public.record_customer_due_payment(
    p_payment_id UUID,
    p_due_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'bKash',
    p_note TEXT DEFAULT ''
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_customer_id BIGINT;
    v_customer_name TEXT;
    v_description TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_new_paid NUMERIC;
    v_new_due NUMERIC;
    v_new_status TEXT;
    v_client_details TEXT;
    v_income_id BIGINT;
    v_existing_payment RECORD;
    v_result JSONB;
BEGIN
    -- 1. Authentication check
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    -- 2. Validate input parameters
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required for idempotency tracking';
    END IF;

    -- 3. Retrieve due record
    SELECT customer_id, customer_name, description, total_amount, paid_amount
    INTO v_customer_id, v_customer_name, v_description, v_total_amount, v_current_paid
    FROM public.customer_dues
    WHERE id = p_due_id AND user_id = v_user_id;

    IF v_customer_name IS NULL THEN
        RAISE EXCEPTION 'Due record not found or access denied';
    END IF;

    -- 4. Check for duplicate payment (Idempotency)
    SELECT * INTO v_existing_payment
    FROM public.customer_due_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded previously. Duplicate request safely skipped.'
        );
    END IF;

    -- 5. Calculate new balances
    v_new_paid := v_current_paid + p_amount;
    v_new_due := GREATEST(0, v_total_amount - v_new_paid);

    IF v_new_due = 0 THEN
        v_new_status := 'Paid';
    ELSE
        v_new_status := 'Partially Paid';
    END IF;

    -- 6. Format client details for Income record
    v_client_details := v_customer_name || ' (' || v_description || ')';

    -- 7. Insert Income record linked to this payment
    INSERT INTO public.income (
        user_id,
        date,
        source,
        client_details,
        amount,
        payment_type,
        month,
        notes
    ) VALUES (
        v_user_id,
        p_payment_date,
        'Customer Payment',
        v_client_details,
        p_amount,
        p_payment_method,
        'Month 1',
        COALESCE(p_note, '')
    )
    RETURNING id INTO v_income_id;

    -- 8. Insert Due Payment record
    INSERT INTO public.customer_due_payments (
        id,
        user_id,
        due_id,
        customer_id,
        amount,
        payment_date,
        payment_method,
        note,
        income_id
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_due_id,
        v_customer_id,
        p_amount,
        p_payment_date,
        p_payment_method,
        COALESCE(p_note, ''),
        v_income_id
    );

    -- 9. Update Customer Dues summary
    UPDATE public.customer_dues
    SET paid_amount = v_new_paid,
        due_amount = v_new_due,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_due_id AND user_id = v_user_id;

    -- 10. Build result object
    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'income_id', v_income_id,
        'due_id', p_due_id,
        'amount', p_amount,
        'new_paid', v_new_paid,
        'new_due', v_new_due,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;

-- ====================================================================
-- LIABILITY / DEBT MANAGEMENT MODULE SCHEMA & POLICIES
-- ====================================================================

-- 17. LIABILITIES TABLE
CREATE TABLE IF NOT EXISTS public.liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    creditor_name TEXT NOT NULL,
    liability_type TEXT NOT NULL DEFAULT 'Hawlad', -- 'Hawlad', 'Bank Loan', 'EMI', 'Other'
    total_amount NUMERIC NOT NULL CHECK (total_amount > 0),
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    remaining_amount NUMERIC NOT NULL DEFAULT 0,
    due_date DATE NULL,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Paid Off')),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 18. LIABILITY PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS public.liability_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) DEFAULT auth.uid(),
    liability_id BIGINT NOT NULL REFERENCES public.liabilities(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    expense_id BIGINT NULL REFERENCES public.expenses(id) ON DELETE SET NULL,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_liabilities_user_id ON public.liabilities(user_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_user_id ON public.liability_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_liability_payments_liability_id ON public.liability_payments(liability_id);

-- RLS
ALTER TABLE public.liabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.liability_payments ENABLE ROW LEVEL SECURITY;

-- POLICIES
DROP POLICY IF EXISTS "Users can select own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can insert own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can update own liabilities" ON public.liabilities;
DROP POLICY IF EXISTS "Users can delete own liabilities" ON public.liabilities;

CREATE POLICY "Users can select own liabilities" ON public.liabilities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liabilities" ON public.liabilities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liabilities" ON public.liabilities FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liabilities" ON public.liabilities FOR DELETE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can select own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can insert own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can update own liability_payments" ON public.liability_payments;
DROP POLICY IF EXISTS "Users can delete own liability_payments" ON public.liability_payments;

CREATE POLICY "Users can select own liability_payments" ON public.liability_payments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own liability_payments" ON public.liability_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own liability_payments" ON public.liability_payments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own liability_payments" ON public.liability_payments FOR DELETE USING (auth.uid() = user_id);

-- ATOMIC RPC FOR RECORDING LIABILITY PAYMENT
CREATE OR REPLACE FUNCTION public.record_liability_payment(
    p_payment_id UUID,
    p_liability_id BIGINT,
    p_payment_date DATE,
    p_amount NUMERIC,
    p_payment_method TEXT DEFAULT 'Cash',
    p_notes TEXT DEFAULT '',
    p_add_to_expense BOOLEAN DEFAULT true
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_creditor_name TEXT;
    v_liability_type TEXT;
    v_total_amount NUMERIC;
    v_current_paid NUMERIC;
    v_existing_payment RECORD;
    v_expense_id BIGINT;
    v_new_paid NUMERIC;
    v_new_remaining NUMERIC;
    v_new_status TEXT;
    v_result JSONB;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;

    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero';
    END IF;

    IF p_payment_id IS NULL THEN
        RAISE EXCEPTION 'Payment ID is required';
    END IF;

    SELECT creditor_name, liability_type, COALESCE(total_amount, 0), COALESCE(paid_amount, 0)
    INTO v_creditor_name, v_liability_type, v_total_amount, v_current_paid
    FROM public.liabilities
    WHERE id = p_liability_id AND user_id = v_user_id;

    IF v_creditor_name IS NULL THEN
        RAISE EXCEPTION 'Liability not found or access denied';
    END IF;

    -- Idempotency check
    SELECT * INTO v_existing_payment
    FROM public.liability_payments
    WHERE id = p_payment_id AND user_id = v_user_id;

    IF v_existing_payment IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success', true,
            'idempotent_retry', true,
            'payment_id', v_existing_payment.id,
            'message', 'Payment already recorded safely.'
        );
    END IF;
    
    -- Insert Expense if requested
    IF p_add_to_expense THEN
        -- Generate a unique BIGINT ID using timestamp to avoid sequence desync issues
        v_expense_id := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;
        
        INSERT INTO public.expenses (
            id,
            user_id,
            date,
            category,
            description,
            amount,
            month,
            notes
        ) VALUES (
            v_expense_id,
            v_user_id,
            p_payment_date,
            v_liability_type || ' Repayment',
            'Repaid to: ' || v_creditor_name,
            p_amount,
            'Month 1',
            COALESCE(p_notes, '')
        );
    END IF;

    -- Insert Payment Record
    INSERT INTO public.liability_payments (
        id,
        user_id,
        liability_id,
        payment_date,
        amount,
        payment_method,
        expense_id,
        notes
    ) VALUES (
        p_payment_id,
        v_user_id,
        p_liability_id,
        p_payment_date,
        p_amount,
        p_payment_method,
        v_expense_id,
        COALESCE(p_notes, '')
    );

    -- Update Liability summary
    v_new_paid := v_current_paid + p_amount;
    v_new_remaining := GREATEST(0, v_total_amount - v_new_paid);
    
    IF v_new_paid >= v_total_amount THEN
        v_new_status := 'Paid Off';
    ELSE
        v_new_status := 'Active';
    END IF;

    UPDATE public.liabilities
    SET paid_amount = v_new_paid,
        remaining_amount = v_new_remaining,
        status = v_new_status,
        updated_at = NOW()
    WHERE id = p_liability_id AND user_id = v_user_id;

    SELECT jsonb_build_object(
        'success', true,
        'payment_id', p_payment_id,
        'expense_id', v_expense_id,
        'new_paid', v_new_paid,
        'new_remaining', v_new_remaining,
        'status', v_new_status
    ) INTO v_result;

    RETURN v_result;
END;
$$;






